// ============================================================
// AP Computer Science Principles Question Bank — Units 1-5
// Paste your questions into each unit array below.
// Format: { q: "Question?", correct: "Right answer", wrong: ["Wrong A", "Wrong B", "Wrong C"] }
// ============================================================

const APCSP_QUESTIONS = {

    // Unit 1: Creative Development
    // Covers: collaboration, program design, development process,
    //         identifying and correcting errors, documentation.
    1: [
{ q: "A mistake in an algorithm or program that causes it to behave unexpectedly is a:", correct: "Logic Error", wrong: ["Syntax Error", "Runtime Error", "Overflow Error"] },
  { q: "A mistake in the 'grammar' of a programming language that prevents the code from running is a:", correct: "Syntax Error", wrong: ["Logic Error", "Runtime Error", "Semantic Error"] },
  { q: "A mistake that occurs while the program is executing, often causing it to crash, is a:", correct: "Runtime Error", wrong: ["Syntax Error", "Design Error", "Logic Error"] },
  { q: "The process of finding and fixing errors in a program is:", correct: "Debugging", wrong: ["Refactoring", "Compiling", "Incremental Development"] },
  { q: "A process that breaks a problem into smaller, manageable sub-problems is:", correct: "Decomposition", wrong: ["Abstraction", "Iteration", "Selection"] },
  { q: "The smallest unit of data in a computer, representing a 0 or a 1, is a:", correct: "Bit", wrong: ["Byte", "Nibble", "Pixel"] },
  { q: "A group of 8 bits is called a:", correct: "Byte", wrong: ["Bit", "Word", "Megabit"] },
  { q: "An error that occurs when a computer attempts to represent a number that is too large for the allocated bits is an:", correct: "Overflow Error", wrong: ["Round-off Error", "Logic Error", "Runtime Error"] },
  { q: "An error that occurs because a computer cannot represent certain fractional values exactly is a:", correct: "Round-off Error", wrong: ["Overflow Error", "Syntax Error", "Binary Error"] },
  { q: "A data compression technique that reduces file size by removing 'useless' or redundant info without losing quality is:", correct: "Lossless Compression", wrong: ["Lossy Compression", "Refactoring", "Binary Encoding"] },
  { q: "A data compression technique that reduces file size by permanently discarding some data, often used in JPEG or MP3 files, is:", correct: "Lossy Compression", wrong: ["Lossless Compression", "Encryption", "Abstraction"] },
  { q: "Information about data, such as the date a photo was taken or the file size, is called:", correct: "Metadata", wrong: ["Hyperdata", "Microdata", "Big Data"] },
  { q: "The base-2 numbering system used by computers consisting of 0s and 1s is:", correct: "Binary", wrong: ["Decimal", "Hexadecimal", "Octal"] },
  { q: "The base-10 numbering system used by humans is:", correct: "Decimal", wrong: ["Binary", "Hexadecimal", "ASCII"] },
  { q: "Which numbering system uses the digits 0-9 and letters A-F?", correct: "Hexadecimal", wrong: ["Binary", "Decimal", "Base-8"] },
  { q: "How many different values can be represented with 4 bits?", correct: "16", wrong: ["4", "8", "32"] },
  { q: "How many different values can be represented with 8 bits?", correct: "256", wrong: ["128", "512", "1024"] },
  { q: "The standard encoding scheme that maps 128 characters to binary numbers is:", correct: "ASCII", wrong: ["RGB", "Unicode", "Metadata"] },
  { q: "The color model that uses varying intensities of Red, Green, and Blue light is:", correct: "RGB", wrong: ["CMYK", "Hex", "Lossy"] },
  { q: "The smallest unit of a digital image, typically a single dot of color, is a:", correct: "Pixel", wrong: ["Bit", "Byte", "Raster"] },
  { q: "A step-by-step set of instructions to solve a problem is an:", correct: "Algorithm", wrong: ["Program", "Function", "Variable"] },
  { q: "A simplified representation of something complex that allows you to focus on the relevant details is an:", correct: "Abstraction", wrong: ["Algorithm", "Iteration", "Binary"] },
  { q: "A collaborative development style where two programmers work at one computer is:", correct: "Pair Programming", wrong: ["Dual Coding", "Split Coding", "Scrum"] },
  { q: "The process of starting with a broad idea and slowly adding detail to a program is:", correct: "Top-Down Design", wrong: ["Bottom-Up Design", "Linear Development", "Agile"] },
  { q: "Documentation that describes the purpose of a program and how it works is:", correct: "Program Documentation", wrong: ["Comments", "Pseudocode", "Metadata"] },
  { q: "A placeholder for a piece of information that can change is a:", correct: "Variable", wrong: ["Constant", "Function", "Literal"] },
  { q: "An approach to development that breaks a project into small, repeating cycles is:", correct: "Iterative Development", wrong: ["Waterfall Development", "Linear Design", "Static Design"] },
  { q: "A collection of data values, usually of the same type, stored under one name is a:", correct: "List (or Array)", wrong: ["Variable", "Function", "Parameter"] },
  { q: "The process of translating high-level code into machine code that a computer can execute is:", correct: "Compiling", wrong: ["Debugging", "Encoding", "Formatting"] },
  { q: "In programming, a 'comment' is used for:", correct: "Explaining code to humans and is ignored by the computer", wrong: ["Changing the logic of the code", "Defining a new variable", "Speeding up the program"] },
  { q: "The specific sequence of bits used to represent a character, number, or image is:", correct: "Digital Representation", wrong: ["Abstraction", "Compression", "Logic"] },
  { q: "Large datasets that are too complex for traditional data-processing software are:", correct: "Big Data", wrong: ["Metadata", "Lossy Data", "Binary Sets"] },
  { q: "An informal way of writing algorithms that looks like code but is meant for humans to read is:", correct: "Pseudocode", wrong: ["Syntax", "Machine Code", "Documentation"] },
  { q: "The binary value of the decimal number 5 is:", correct: "101", wrong: ["111", "011", "100"] },
  { q: "Which of the following is a benefit of using hexadecimal over binary?", correct: "It is more concise and easier for humans to read", wrong: ["It uses fewer bits in memory", "It is the only language computers understand", "It prevents logic errors"] },
  { q: "A set of rules for how to behave and communicate in a collaborative environment is:", correct: "Code of Conduct", wrong: ["Syntax", "Algorithm", "Documentation"] },
  { q: "Using a program to model the behavior of a real-world system is a:", correct: "Simulation", wrong: ["Decomposition", "Iteration", "Selection"] },
  { q: "Data that can only take on certain discrete values (like 0 or 1) is:", correct: "Digital Data", wrong: ["Analog Data", "Linear Data", "Continuous Data"] },
  { q: "Data that is continuous and can take on any value (like a vinyl record or mercury thermometer) is:", correct: "Analog Data", wrong: ["Digital Data", "Binary Data", "Discrete Data"] },
  { q: "Converting analog data into digital data by measuring the analog signal at regular intervals is:", correct: "Sampling", wrong: ["Compressing", "Encoding", "Decoding"] },
  { q: "What is the largest decimal number you can represent with 3 bits?", correct: "7", wrong: ["3", "8", "9"] },
  { q: "Which compression type is best for a text document where every word must remain exact?", correct: "Lossless", wrong: ["Lossy", "Sampling", "Binary"] },
  { q: "Which compression type is best for streaming video where some quality can be sacrificed for speed?", correct: "Lossy", wrong: ["Lossless", "Metadata", "Hexadecimal"] },
  { q: "Cleaning and organizing data to make it easier to analyze is:", correct: "Data Filtering", wrong: ["Data Compression", "Sampling", "Abstraction"] },
  { q: "Using software to find patterns or trends in a large dataset is:", correct: "Data Mining", wrong: ["Data Storage", "Encryption", "Debugging"] },
  { q: "In the RGB color model, (255, 255, 255) represents:", correct: "White", wrong: ["Black", "Red", "Gray"] },
  { q: "In the RGB color model, (0, 0, 0) represents:", correct: "Black", wrong: ["White", "Blue", "Green"] },
  { q: "A visualization that shows the frequency of data values is a:", correct: "Histogram", wrong: ["Scatter Plot", "Pie Chart", "Table"] },
  { q: "The practice of using public data to make discoveries is:", correct: "Open Data", wrong: ["Crowdsourcing", "Lossy Compression", "Metadata"] },
  { q: "Obtaining input or information from a large number of people via the internet is:", correct: "Crowdsourcing", wrong: ["Data Mining", "Collaboration", "Sampling"] },
  { q: "Which of the following is NOT an example of metadata?", correct: "The actual words in a text file", wrong: ["The author of a document", "The resolution of an image", "The GPS coordinates of a photo"] },
  { q: "The binary value '1111' is equal to which decimal number?", correct: "15", wrong: ["4", "8", "16"] },
  { q: "The binary value '1000' is equal to which decimal number?", correct: "8", wrong: ["1", "4", "16"] },
  { q: "What color is represented by (255, 0, 0) in RGB?", correct: "Red", wrong: ["Green", "Blue", "Yellow"] },
  { q: "What color is represented by (0, 255, 0) in RGB?", correct: "Green", wrong: ["Red", "Cyan", "Magenta"] },
  { q: "The binary value '11' is equal to decimal:", correct: "3", wrong: ["2", "4", "1"] },
  { q: "The binary value '1010' is equal to decimal:", correct: "10", wrong: ["12", "5", "8"] },
  { q: "Adding a '0' to the end of a binary number (e.g., 101 to 1010) does what to the value?", correct: "Multiplies it by 2", wrong: ["Adds 10", "Divides it by 2", "Adds 1"] },
  { q: "Removing a digit from the end of a binary number does what to the value?", correct: "Divides it by 2 (integer division)", wrong: ["Subtracts 1", "Multiplies it by 2", "Subtracts 10"] },
  { q: "A visual representation of an algorithm using shapes and arrows is a:", correct: "Flowchart", wrong: ["Pseudocode", "Circuit Diagram", "List"] },
  { q: "The process of looking at data and asking 'What does this mean?' is:", correct: "Data Interpretation", wrong: ["Data Collection", "Data Cleansing", "Data Sampling"] },
  { q: "What happens to the number of possible values when you add 1 bit to a binary sequence?", correct: "It doubles", wrong: ["It increases by 1", "It stays the same", "It triples"] },
  { q: "An abstraction that replaces a block of code with a single name is a:", correct: "Procedure (or Function)", wrong: ["Variable", "Loop", "Comment"] },
  { q: "When two people work together to find a solution, they are:", correct: "Collaborating", wrong: ["Compressing", "Abstracting", "Iterating"] },
  { q: "A set of values and the operations that can be performed on them is a:", correct: "Data Type", wrong: ["Binary Code", "Logic Gate", "Variable"] },
  { q: "If you want to represent 100 different items, what is the minimum number of bits needed?", correct: "7 bits", wrong: ["6 bits", "8 bits", "100 bits"] },
  { q: "If you have 5 bits, how many unique patterns can you create?", correct: "32", wrong: ["5", "10", "25"] },
  { q: "Which numbering system is base-16?", correct: "Hexadecimal", wrong: ["Binary", "Octal", "Decimal"] },
  { q: "True or False: Information lost during lossy compression can be recovered.", correct: "False", wrong: ["True"] },
  { q: "True or False: Lossless compression results in a smaller file than lossy compression usually.", correct: "False", wrong: ["True"] },
  { q: "The main goal of abstraction is to:", correct: "Manage complexity", wrong: ["Speed up the CPU", "Reduce power consumption", "Prevent all bugs"] },
  { q: "A programmer who creates a library for others to use is providing an:", correct: "API", wrong: ["Algorithm", "Iterative cycle", "Overflow"] },
  { q: "Information that is accessible to anyone is:", correct: "Public Data", wrong: ["Private Data", "Encrypted Data", "Lossy Data"] },
  { q: "A problem that is too large for one computer to solve might use:", correct: "Parallel Computing", wrong: ["Lossless Compression", "Binary Encoding", "Manual Sorting"] },
  { q: "Transforming data to hide its meaning is:", correct: "Encryption", wrong: ["Compression", "Cleansing", "Filtering"] }
    ],

    // Unit 2: Data
    // Covers: binary/data representation, data compression,
    //         extracting information from data, using programs with data.
    2: [
{ q: "A group of interconnected computing devices capable of sending or receiving data is a:", correct: "Computer Network", wrong: ["Internet", "Router", "Protocol"] },
  { q: "The global system of interconnected computer networks is the:", correct: "Internet", wrong: ["World Wide Web", "Ethernet", "LAN"] },
  { q: "A set of rules governing the exchange or transmission of data between devices is a:", correct: "Protocol", wrong: ["Algorithm", "Law", "Metadata"] },
  { q: "The capacity for the system to change in size and scale to meet new demands is:", correct: "Scalability", wrong: ["Redundancy", "Routing", "Bandwidth"] },
  { q: "The maximum amount of data that can be sent in a fixed amount of time is:", correct: "Bandwidth", wrong: ["Latency", "Speed", "Frequency"] },
  { q: "The time it takes for a bit to travel from its sender to its receiver is:", correct: "Latency", wrong: ["Bandwidth", "Bit rate", "Ping"] },
  { q: "A type of computer that forwards data across a network is a:", correct: "Router", wrong: ["Switch", "Server", "Hub"] },
  { q: "The process of finding a path from sender to receiver is:", correct: "Routing", wrong: ["Switching", "Protocolling", "Addressing"] },
  { q: "A chunk of data sent over a network is a:", correct: "Packet", wrong: ["Bit", "File", "Segment"] },
  { q: "The inclusion of extra components so that a system can continue to work even if individual components fail is:", correct: "Redundancy", wrong: ["Scalability", "Fault Tolerance", "Efficiency"] },
  { q: "A system that can continue to function even in the event of individual component failures is:", correct: "Fault Tolerant", wrong: ["Scalability", "Redundant", "High Bandwidth"] },
  { q: "The protocol used for transmitting web pages over the internet is:", correct: "HTTP", wrong: ["IP", "TCP", "DNS"] },
  { q: "A unique number assigned to each device on the internet is an:", correct: "IP Address", wrong: ["MAC Address", "URL", "Port Number"] },
  { q: "The system that translates human-friendly domain names (like google.com) into IP addresses is:", correct: "DNS", wrong: ["HTTP", "TCP", "UDP"] },
  { q: "The protocol that provides reliable, error-checked delivery of a stream of packets is:", correct: "TCP", wrong: ["UDP", "IP", "HTTP"] },
  { q: "The protocol that provides fast, but unreliable, delivery of packets (used for video streaming) is:", correct: "UDP", wrong: ["TCP", "IP", "DNS"] },
  { q: "The hierarchical addressing system that ensures data reaches the correct destination is:", correct: "IP (Internet Protocol)", wrong: ["HTTP", "SMTP", "Ethernet"] },
  { q: "The protocol used to encrypt data sent over the web is:", correct: "HTTPS", wrong: ["HTTP", "TCP", "FTP"] },
  { q: "A system of linked pages, programs, and files that is accessed via the internet is the:", correct: "World Wide Web", wrong: ["Internet", "Cloud", "Ethernet"] },
  { q: "The principle that all-internet traffic should be treated equally by Internet Service Providers is:", correct: "Net Neutrality", wrong: ["Open Access", "Digital Divide", "Fair Use"] },
  { q: "The differing access to computing devices and the internet based on socioeconomic or geographic factors is the:", correct: "Digital Divide", wrong: ["Net Neutrality", "Censorship", "Bandwidth Gap"] },
  { q: "An attack that attempts to make a computer or network resource unavailable by flooding it with traffic is a:", correct: "DDoS Attack", wrong: ["Phishing Attack", "Malware", "Man-in-the-Middle"] },
  { q: "A cryptographic system that uses two keys—a public key known to everyone and a private key known only to the recipient—is:", correct: "Public Key Encryption", wrong: ["Symmetric Encryption", "Substitution Cipher", "Caesar Cipher"] },
  { q: "A method of encryption where the same key is used to both encrypt and decrypt a message is:", correct: "Symmetric Encryption", wrong: ["Asymmetric Encryption", "Public Key Encryption", "Certificate Authority"] },
  { q: "A digital document issued by a trusted third party that verifies the ownership of a public key is a:", correct: "Digital Certificate", wrong: ["Cookie", "Password", "Private Key"] },
  { q: "Entities that verify the identities of websites and issue digital certificates are:", correct: "Certificate Authorities", wrong: ["Internet Service Providers", "Routers", "Web Browsers"] },
  { q: "A 'malicious software' intended to damage or take partial control over a computer system is:", correct: "Malware", wrong: ["Firmware", "Shareware", "Adware"] },
  { q: "Software that records every letter typed on a keyboard to steal passwords is a:", correct: "Keylogger", wrong: ["Virus", "Worm", "Trojan"] },
  { q: "A technique that attempts to trick a user into providing personal information, often via fake emails, is:", correct: "Phishing", wrong: ["DDoS", "Ransomware", "Spoofing"] },
  { q: "Malware that encrypts a user's files and demands payment to unlock them is:", correct: "Ransomware", wrong: ["Spyware", "Adware", "Worm"] },
  { q: "The use of a program to record and intercept data packets as they flow across a network is:", correct: "Packet Sniffing", wrong: ["Routing", "DNS Lookup", "Redundancy"] },
  { q: "A computer program that can replicate itself and spread from one computer to another is a:", correct: "Virus", wrong: ["Logic Bomb", "Script", "Cookie"] },
  { q: "A security measure that requires two different forms of identification to access an account is:", correct: "Multi-factor Authentication", wrong: ["Strong Passwords", "Encryption", "Firewalls"] },
  { q: "A 'strong' password should typically include:", correct: "A mix of letters, numbers, symbols, and length", wrong: ["Your birthdate", "Sequential numbers like 1234", "Your username"] },
  { q: "The 'openness' of the internet protocols (like IP and TCP) allows for:", correct: "Interoperability between different types of devices", wrong: ["Automatic deletion of viruses", "Guaranteed 100% security", "Free high-speed internet for everyone"] },
  { q: "Who manages the IP addresses and domain names globally?", correct: "ICANN", wrong: ["Google", "The US Government", "Cisco"] },
  { q: "Which protocol is 'connectionless' and 'best-effort'?", correct: "UDP", wrong: ["TCP", "HTTP", "FTP"] },
  { q: "An IP address (IPv4) consists of how many bits?", correct: "32 bits", wrong: ["16 bits", "64 bits", "128 bits"] },
  { q: "An IPv6 address consists of how many bits?", correct: "128 bits", wrong: ["32 bits", "64 bits", "256 bits"] },
  { q: "Why was IPv6 created?", correct: "To provide more IP addresses because IPv4 was running out", wrong: ["To make the internet faster", "To replace the World Wide Web", "To eliminate the need for routers"] },
  { q: "When a packet is lost in a TCP connection, what happens?", correct: "The receiver requests it be resent and TCP manages the retransmission", wrong: ["The entire file is deleted", "The internet crashes", "The packet is ignored and the file is corrupted"] },
  { q: "The path that data takes through the internet is:", correct: "Dynamic and can change based on traffic", wrong: ["Fixed and never changes", "Determined solely by the sender", "Stored in the DNS server"] },
  { q: "A domain name like 'education.github.io' has the top-level domain of:", correct: ".io", wrong: ["education", "github", "http"] },
  { q: "The part of the URL 'https://' indicates the:", correct: "Protocol", wrong: ["Domain", "Path", "Resource"] },
  { q: "The 'end-to-end' architecture of the internet means:", correct: "Complex functions happen at the edges, while the core stays simple", wrong: ["Routers do all the heavy lifting", "Data only travels in one direction", "The internet has a single 'off' switch"] },
  { q: "A network of private computers infected with malware and controlled as a group is a:", correct: "Botnet", wrong: ["LAN", "Server Farm", "Intranet"] },
  { q: "Which of the following is a symptom of a DDoS attack?", correct: "A website becomes slow or inaccessible to legitimate users", wrong: ["Your password is changed automatically", "Your screen turns blue", "Your files are deleted"] },
  { q: "What does the 'S' in HTTPS stand for?", correct: "Secure", wrong: ["Standard", "System", "Sync"] },
  { q: "A sub-domain is found to the ________ of the main domain name.", correct: "Left", wrong: ["Right", "Top", "Bottom"] },
  { q: "The 'World Wide Web' uses which protocol to request and send data?", correct: "HTTP", wrong: ["SMTP", "IP", "DNS"] },
  { q: "Fiber optic cables transmit data using:", correct: "Light", wrong: ["Electricity", "Radio waves", "Sound"] },
  { q: "Ethernet cables transmit data using:", correct: "Electricity", wrong: ["Light", "Air", "Magnetism"] },
  { q: "WiFi transmits data using:", correct: "Radio waves", wrong: ["Light", "Cables", "Heat"] },
  { q: "The time delay between a request and a response is:", correct: "Latency", wrong: ["Bandwidth", "Bitrate", "Packet loss"] },
  { q: "A router's main job is to:", correct: "Direct packets toward their destination", wrong: ["Store web pages", "Create IP addresses", "Host websites"] },
  { q: "True or False: The internet is controlled by a single centralized organization.", correct: "False", wrong: ["True"] },
  { q: "True or False: DNS is a centralized system with only one server.", correct: "False", wrong: ["True"] },
  { q: "When you type a URL, your computer first checks ________ for the IP address.", correct: "A DNS Resolver", wrong: ["The Router", "The Web Page", "The CPU"] },
  { q: "What ensures that a packet reaches the right *application* (like a browser vs email) on a computer?", correct: "Port Numbers", wrong: ["IP Addresses", "MAC Addresses", "Domain Names"] },
  { q: "The internet was designed to be ________, meaning it can survive even if parts are destroyed.", correct: "Decentralized", wrong: ["Centralized", "Private", "Linear"] },
  { q: "The 'digital certificate' used in HTTPS is validated by:", correct: "A Browser", wrong: ["An ISP", "The Router", "The BIOS"] },
  { q: "What is the primary vulnerability of symmetric encryption?", correct: "Securely sharing the key with the other person", wrong: ["It is very slow", "It is easily guessed by computers", "It only works for text"] },
  { q: "Asymmetric encryption solves the key-sharing problem by using:", correct: "A Public Key and a Private Key", wrong: ["Two Private Keys", "Two Public Keys", "One shared password"] },
  { q: "The Caesar Cipher is an example of:", correct: "Symmetric Encryption", wrong: ["Asymmetric Encryption", "Public Key Cryptography", "Digital Certification"] },
  { q: "Checking that data has not been altered during transmission is an example of:", correct: "Data Integrity", wrong: ["Data Confidentiality", "Data Availability", "Redundancy"] },
  { q: "Which protocol breaks data into packets and numbers them?", correct: "TCP", wrong: ["IP", "UDP", "HTTP"] },
  { q: "In a network diagram, a 'node' represents:", correct: "Any device connected to the network", wrong: ["Only a router", "Only a cable", "A virus"] },
  { q: "The internet is a 'network of ________'.", correct: "Networks", wrong: ["Computers", "Cables", "People"] },
  { q: "The term for data being sent in a way that doesn't reveal the sender's identity is:", correct: "Anonymity", wrong: ["Encryption", "Routing", "Phishing"] },
  { q: "A 'Firewall' is used to:", correct: "Filter incoming and outgoing network traffic", wrong: ["Speed up the internet", "Charge for bandwidth", "Replace a router"] },
  { q: "A piece of data that a website stores on your computer to 'remember' you is a:", correct: "Cookie", wrong: ["Packet", "Script", "Cache"] },
  { q: "Which of the following is a physical medium used to connect a network?", correct: "Copper wire", wrong: ["TCP", "Binary", "Browser"] },
  { q: "Routers use 'Routing ________' to decide the best path for a packet.", correct: "Tables", wrong: ["Scripts", "Caches", "Logbooks"] },
  { q: "If a system has 3 paths between two nodes, and 2 fail, the nodes can still communicate. This is:", correct: "Fault Tolerance", wrong: ["Scalability", "Latency", "Bandwidth"] },
  { q: "The 'Internet of Things' (IoT) refers to:", correct: "Everyday objects being connected to the internet", wrong: ["The history of the internet", "A type of web browser", "Buying things only online"] }
    ],

    // Unit 3: Algorithms and Programming
    // Covers: variables, data types, expressions, conditionals, loops,
    //         procedures, lists, searching/sorting, simulations.
    3: [
  { q: "The execution of instructions in the exact order they are written is:", correct: "Sequencing", wrong: ["Selection", "Iteration", "Recursion"] },
  { q: "Using a condition to determine which part of an algorithm to execute is:", correct: "Selection", wrong: ["Sequencing", "Iteration", "Abstraction"] },
  { q: "The repeating of a set of instructions a specific number of times or until a condition is met is:", correct: "Iteration", wrong: ["Selection", "Sequencing", "Concatenation"] },
  { q: "A Boolean value can only be:", correct: "True or False", wrong: ["1 or 2", "Yes, No, or Maybe", "Any number"] },
  { q: "Which operator is used to check if two values are equal in most languages?", correct: "==", wrong: ["=", "!=", "+="] },
  { q: "Which operator represents 'Not Equal'?", correct: "!=", wrong: ["==", "=", "<>"] },
  { q: "The operator used to find the remainder of a division problem is:", correct: "Mod (Modulo)", wrong: ["Div", "Root", "Exp"] },
  { q: "A named group of programming instructions that may have parameters and return a value is a:", correct: "Procedure (or Function)", wrong: ["Variable", "Loop", "Condition"] },
  { q: "Input variables of a procedure that act as placeholders are:", correct: "Parameters", wrong: ["Arguments", "Results", "Return values"] },
  { q: "The specific values passed to a procedure when it is called are:", correct: "Arguments", wrong: ["Parameters", "Placeholders", "Labels"] },
  { q: "A list is an example of a(n) ________ because it allows us to group multiple items together.", correct: "Data Abstraction", wrong: ["Procedural Abstraction", "Iterative Abstraction", "Selection Abstraction"] },
  { q: "An algorithm that checks every item in a list from start to finish is a:", correct: "Linear Search", wrong: ["Binary Search", "Random Search", "Bubble Search"] },
  { q: "A search algorithm that starts at the middle of a *sorted* list and eliminates half the items each step is a:", correct: "Binary Search", wrong: ["Linear Search", "Sequential Search", "Merge Search"] },
  { q: "Which search algorithm is more efficient for a very large sorted list?", correct: "Binary Search", wrong: ["Linear Search", "Selection Search", "Iterative Search"] },
  { q: "An algorithm with 'Linear' efficiency means as the list size doubles, the time taken:", correct: "Doubles", wrong: ["Stays the same", "Squares", "Halves"] },
  { q: "An algorithm with 'Logarithmic' efficiency means as the list size doubles, the time taken:", correct: "Increases by a small constant amount", wrong: ["Doubles", "Squares", "Decreases"] },
  { q: "The measure of how many steps an algorithm takes relative to the size of the input is:", correct: "Efficiency", wrong: ["Correctness", "Readability", "Abstraction"] },
  { q: "A problem for which no algorithm can be constructed that always leads to a correct yes-or-no answer is an:", correct: "Undecidable Problem", wrong: ["Unsolvable Problem", "Complex Problem", "Linear Problem"] },
  { q: "An algorithm that can solve a problem in 'Reasonable Time' has an efficiency that is:", correct: "Polynomial (Constant, Linear, Squared, etc.)", wrong: ["Exponential", "Factorial", "Infinite"] },
  { q: "An algorithm that takes 'Unreasonable Time' often has an efficiency that is:", correct: "Exponential or Factorial", wrong: ["Linear", "Logarithmic", "Polynomial"] },
  { q: "A 'Heuristic' algorithm is used when:", correct: "Finding the exact best solution takes too long, so a 'good enough' one is used", wrong: ["The computer is too slow to run binary search", "The problem is undecidable", "The programmer doesn't know the math"] },
  { q: "A Boolean 'AND' expression is true only if:", correct: "Both inputs are true", wrong: ["At least one input is true", "Neither input is true", "Both inputs are false"] },
  { q: "A Boolean 'OR' expression is true if:", correct: "At least one input is true", wrong: ["Both inputs must be true", "Both inputs must be false", "Only the first input is true"] },
  { q: "A Boolean 'NOT' expression does what?", correct: "Flips the value (True to False, or vice versa)", wrong: ["Makes everything false", "Makes everything true", "Adds two values"] },
  { q: "Joining two strings of text together is called:", correct: "Concatenation", wrong: ["Integration", "Summation", "Iteration"] },
  { q: "The index of the first element in a list in the AP CSP pseudocode is:", correct: "1", wrong: ["0", "-1", "Index"] },
  { q: "Accessing an element in a list that does not exist results in an:", correct: "Index Out of Bounds Error", wrong: ["Logic Error", "Syntax Error", "Overflow Error"] },
  { q: "A loop that never ends because the condition is always true is an:", correct: "Infinite Loop", wrong: ["Finite Loop", "Recursion", "Nested Loop"] },
  { q: "Placing one loop inside another loop is called:", correct: "Nesting", wrong: ["Layering", "Clustering", "Branching"] },
  { q: "The process of reducing a list to only the elements that meet a certain criteria is:", correct: "Filtering", wrong: ["Mapping", "Reducing", "Sorting"] },
  { q: "Transforming every element in a list (e.g., doubling all numbers) is:", correct: "Mapping", wrong: ["Filtering", "Sorting", "Slicing"] },
  { q: "Combining all elements in a list into a single value (e.g., finding the sum) is:", correct: "Reducing", wrong: ["Filtering", "Mapping", "Traversing"] },
  { q: "The process of going through every item in a list one by one is:", correct: "Traversing", wrong: ["Selecting", "Returning", "Appending"] },
  { q: "Adding a new item to the end of a list is usually called:", correct: "Appending", wrong: ["Inserting", "Indexing", "Splicing"] },
  { q: "Variables that can be accessed from any part of a program are:", correct: "Global Variables", wrong: ["Local Variables", "Static Variables", "Private Variables"] },
  { q: "Variables that can only be accessed within the function or loop where they were defined are:", correct: "Local Variables", wrong: ["Global Variables", "Public Variables", "Constant Variables"] },
  { q: "A value passed *back* from a procedure to the part of the program that called it is a:", correct: "Return Value", wrong: ["Parameter", "Argument", "Global Variable"] },
  { q: "The use of 'Random(a, b)' generates a number between:", correct: "a and b inclusive", wrong: ["a and b exclusive", "0 and a", "Only a and b"] },
  { q: "A programming language that uses pre-defined blocks to create code is:", correct: "Block-based Language", wrong: ["Text-based Language", "Machine Language", "Assembly"] },
  { q: "A programming language where you type out instructions using a specific syntax is a:", correct: "Text-based Language", wrong: ["Block-based Language", "Visual Language", "Logic Language"] },
  { q: "If 'score' is 10, what is the value of 'score > 5 AND score < 10'?", correct: "False", wrong: ["True", "10", "Error"] },
  { q: "If 'score' is 10, what is the value of 'score >= 10 OR score < 5'?", correct: "True", wrong: ["False", "10", "Error"] },
  { q: "The 'Mod' of 10 mod 3 is:", correct: "1", wrong: ["3", "0", "10"] },
  { q: "The 'Mod' of 12 mod 4 is:", correct: "0", wrong: ["3", "4", "1"] },
  { q: "What is the result of 'NOT (True OR False)'?", correct: "False", wrong: ["True", "Error", "Null"] },
  { q: "What is the result of '(True AND False) OR True'?", correct: "True", wrong: ["False", "Error", "Null"] },
  { q: "In programming, 'state' refers to:", correct: "The current value of all variables in a program", wrong: ["The physical location of the computer", "The type of language being used", "The speed of the CPU"] },
  { q: "Which logic gate outputs True only if both inputs are False?", correct: "NOR", wrong: ["AND", "OR", "NAND"] },
  { q: "The ability of a program to solve a problem correctly is its:", correct: "Correctness", wrong: ["Efficiency", "Complexity", "Scalability"] },
  { q: "A 'Library' in programming is:", correct: "A collection of procedures that can be used in different programs", wrong: ["A place to store physical books about code", "A type of variable", "The memory inside the CPU"] },
  { q: "When you use a library function without knowing its internal code, you are using:", correct: "Procedural Abstraction", wrong: ["Data Abstraction", "Logic Abstraction", "Iteration"] },
  { q: "The 'Halting Problem' is an example of an:", correct: "Undecidable Problem", wrong: ["Exponential Problem", "Linear Problem", "Easy Problem"] },
  { q: "If an algorithm's time is $2^n$, where $n$ is input size, it is:", correct: "Unreasonable/Exponential", wrong: ["Reasonable/Polynomial", "Constant", "Linear"] },
  { q: "Using a computer to solve a problem by trying every possible combination is:", correct: "Brute Force", wrong: ["Heuristic", "Binary Search", "Optimization"] },
  { q: "Which of the following is NOT an iterative structure?", correct: "If-Else", wrong: ["For Loop", "While Loop", "Repeat Until"] },
  { q: "The part of an 'If' statement that runs if the condition is False is the:", correct: "Else", wrong: ["Then", "Return", "Break"] },
  { q: "A 'Switch' or 'Case' statement is a shorthand for:", correct: "Multiple If-Else statements", wrong: ["A while loop", "A function call", "A list declaration"] },
  { q: "The process of simplifying code to make it easier to maintain is:", correct: "Refactoring", wrong: ["Compiling", "Sampling", "Traversing"] },
  { q: "Computer science is fundamentally the study of:", correct: "Algorithms and Information", wrong: ["Hardware repair", "Gaming", "Typing fast"] },
  { q: "An algorithm that finishes in $n^2$ steps is:", correct: "Polynomial/Reasonable", wrong: ["Exponential/Unreasonable", "Logarithmic", "Constant"] },
  { q: "True or False: An undecidable problem can be solved for some specific inputs.", correct: "True", wrong: ["False"] },
  { q: "The input size $n$ usually refers to:", correct: "The number of items in the list or data set", wrong: ["The speed of the processor", "The number of lines of code", "The size of the variable"] },
  { q: "Which of the following is a benefit of using procedures?", correct: "Reduces code duplication and makes it easier to update", wrong: ["Makes the code run slower", "Increases the number of bugs", "Eliminates the need for variables"] },
  { q: "A variable that exists only during the execution of a procedure is:", correct: "Local", wrong: ["Global", "Static", "Permanent"] },
  { q: "What is the value of 'count' after: count = 5; count = count + 2; count = 10?", correct: "10", wrong: ["5", "7", "17"] },
  { q: "What is the index of 'B' in list ['A', 'B', 'C'] in CSP pseudocode?", correct: "2", wrong: ["1", "0", "3"] },
  { q: "Which loop is best when you know exactly how many times to repeat?", correct: "For Loop (or Repeat n times)", wrong: ["While Loop", "Repeat Until", "If-Else"] },
  { q: "Which loop is best when you don't know the number of repetitions in advance?", correct: "While Loop (or Repeat Until)", wrong: ["For Loop", "Repeat n times", "Sequence"] },
  { q: "What is '13 MOD 5'?", correct: "3", wrong: ["2", "1", "5"] },
  { q: "If a list has 10 elements, what is the index of the last element?", correct: "10", wrong: ["9", "11", "0"] },
  { q: "Changing the order of instructions in a sequence:", correct: "Can completely change the outcome of the program", wrong: ["Never changes the outcome", "Only changes the speed", "Is called nesting"] },
  { q: "The diamond shape in a flowchart usually represents:", correct: "Selection (A decision)", wrong: ["Start/End", "Process/Instruction", "Input/Output"] },
  { q: "The rectangle shape in a flowchart usually represents:", correct: "A process or instruction", wrong: ["A decision", "Start/End", "A loop"] },
  { q: "A 'Flag' variable is usually a:", correct: "Boolean used to track if a condition has been met", wrong: ["Number used for counting", "String used for names", "List used for storage"] },
  { q: "The logic gate that is True if either A or B is true, but NOT both, is:", correct: "XOR", wrong: ["OR", "AND", "NAND"] }
    ],

    // Unit 4: Computer Systems and Networks
    // Covers: the internet, TCP/IP, fault tolerance, parallel/distributed
    //         computing, cybersecurity, encryption.
    4: [
{ q: "Finding patterns in data to make predictions is known as:", correct: "Data Mining", wrong: ["Data Entry", "Data Filtering", "Data Cleansing"] },
  { q: "The process of making data uniform without changing its meaning is:", correct: "Data Cleaning (or Standardizing)", wrong: ["Data Mining", "Data Encryption", "Data Loss"] },
  { q: "A bias in which a dataset does not represent the entire population accurately is:", correct: "Selection Bias", wrong: ["Confirmation Bias", "Logic Bias", "Algorithmic Bias"] },
  { q: "When an algorithm produces unfair results due to biased training data, it is:", correct: "Algorithmic Bias", wrong: ["Hardware Failure", "Syntax Error", "Logic Error"] },
  { q: "Large datasets that can be analyzed to reveal trends and associations are:", correct: "Big Data", wrong: ["Metadata", "Small Data", "Lossy Data"] },
  { q: "A law that protects 'original works of authorship' like software or music is:", correct: "Copyright", wrong: ["Patent", "Trademark", "Creative Commons"] },
  { q: "A type of license that allows creators to tell the public how their work can be used for free is:", correct: "Creative Commons", wrong: ["Copyright", "Open Source", "Public Domain"] },
  { q: "Works that are no longer protected by copyright and can be used by anyone are in the:", correct: "Public Domain", wrong: ["Creative Commons", "Open Source", "Encrypted Cloud"] },
  { q: "Software that is made available with its source code and can be modified by anyone is:", correct: "Open Source", wrong: ["Closed Source", "Proprietary", "Shareware"] },
  { q: "The legal right to keep your personal information away from the public eye is:", correct: "Privacy", wrong: ["Security", "Encryption", "Integrity"] },
  { q: "Any information that can be used to identify a specific individual (e.g., SSN, Name) is:", correct: "Personally Identifiable Information (PII)", wrong: ["Metadata", "Public Data", "Open Data"] },
  { q: "A 'Cookie' is a small text file used by websites to:", correct: "Track user activity and save preferences", wrong: ["Delete viruses", "Store the website's HTML", "Encrypt your hard drive"] },
  { q: "A policy that explains how a company collects and uses your data is a:", correct: "Privacy Policy", wrong: ["Terms of Service", "EULA", "Copyright"] },
  { q: "The practice of using data to convince or manipulate people's opinions is:", correct: "Targeted Advertising / Persuasion", wrong: ["Data Cleansing", "Data Encryption", "Data Compression"] },
  { q: "The ability of a system to protect data from unauthorized access is:", correct: "Security", wrong: ["Privacy", "Scalability", "Redundancy"] },
  { q: "Using multiple CPUs to run different parts of a program at the same time is:", correct: "Parallel Computing", wrong: ["Sequential Computing", "Distributed Computing", "Serial Processing"] },
  { q: "Using multiple computers to solve a single large problem is:", correct: "Distributed Computing", wrong: ["Parallel Computing", "Sequential Computing", "Cloud Storage"] },
  { q: "A system that uses 'Crowdsourcing' relies on:", correct: "Input from many different people", wrong: ["One very fast computer", "A single expert", "A government database"] },
  { q: "Which of the following can help protect your PII online?", correct: "Using a VPN and multi-factor authentication", wrong: ["Posting your birthday on social media", "Using the same password for all sites", "Clicking on every link in emails"] },
  { q: "The 'Digital Divide' can be caused by lack of:", correct: "Infrastructure, money, or digital literacy", wrong: ["Metadata", "Binary code", "HTML tags"] },
  { q: "Which of the following is a potential risk of Big Data?", correct: "Loss of privacy and potential for discrimination", wrong: ["Smaller file sizes", "Faster internet speeds", "Higher resolution images"] },
  { q: "True or False: Metadata can sometimes be used to identify a person even if their name is removed.", correct: "True", wrong: ["False"] },
  { q: "A program that appears useful but contains malicious code is a:", correct: "Trojan Horse", wrong: ["Virus", "Worm", "Spyware"] },
  { q: "A method of gathering data by asking people to perform tasks or solve problems is:", correct: "Citizen Science", wrong: ["Data Mining", "Machine Learning", "Phishing"] },
  { q: "Which license allows you to use work but requires you to give credit to the author?", correct: "Attribution (CC BY)", wrong: ["Non-Commercial", "No Derivatives", "Public Domain"] },
  { q: "Which license allows you to use work but prevents you from making money off it?", correct: "Non-Commercial (CC NC)", wrong: ["Attribution", "Share-Alike", "Public Domain"] },
  { q: "If you want to use a copyrighted image for a school project, it might fall under:", correct: "Fair Use", wrong: ["Plagiarism", "Public Domain", "Creative Commons"] },
  { q: "A graph that shows how two variables relate to each other is a:", correct: "Scatter Plot", wrong: ["Pie Chart", "Histogram", "Table"] },
  { q: "The practice of moving data storage and processing to the internet rather than local hard drives is:", correct: "Cloud Computing", wrong: ["Edge Computing", "Local Hosting", "Hardwired Storage"] },
  { q: "Using sensors in a city to track traffic patterns is an example of:", correct: "Ubiquitous Computing (or IoT)", wrong: ["Manual Sampling", "Phishing", "Linear Search"] },
  { q: "A data set that is 'unstructured' might include:", correct: "Emails, social media posts, and videos", wrong: ["Excel spreadsheets", "SQL databases", "Binary files"] },
  { q: "A data set that is 'structured' is usually organized in:", correct: "Tables with rows and columns", wrong: ["Random text files", "Voice recordings", "Images"] },
  { q: "Targeting people with news or ads based on their previous online behavior is:", correct: "Micro-targeting", wrong: ["Broadcasting", "Crowdsourcing", "Encryption"] },
  { q: "The gap between those who have high-speed internet and those who don't is:", correct: "The Broadband Gap", wrong: ["The Latency Divide", "The Logic Gap", "The Binary Gap"] },
  { q: "Which of the following is a way to reduce bias in a machine learning model?", correct: "Using a diverse and representative training dataset", wrong: ["Using only data from one city", "Letting the computer pick its own data", "Removing all labels from the data"] },
  { q: "What is the primary purpose of a 'Terms of Service' agreement?", correct: "To define the legal relationship between the user and the provider", wrong: ["To teach you how to use the software", "To speed up the download", "To encrypt your password"] },
  { q: "A visual way to display the relationship between different parts of a whole is a:", correct: "Pie Chart", wrong: ["Scatter Plot", "Bar Graph", "Line Graph"] },
  { q: "Data about a population (age, gender, income) is called:", correct: "Demographics", wrong: ["Metadata", "Binary Data", "Psychographics"] },
  { q: "The 'Right to be Forgotten' allows individuals to:", correct: "Request that personal data be deleted from search engines/websites", wrong: ["Change their name legally", "Delete other people's posts", "Get free internet"] },
  { q: "In data science, an 'Outlier' is:", correct: "A data point that is significantly different from others in the set", wrong: ["The most common value", "The average value", "A missing data point"] },
  { q: "The average of a set of numbers is the:", correct: "Mean", wrong: ["Median", "Mode", "Range"] },
  { q: "The middle value in a sorted list of numbers is the:", correct: "Median", wrong: ["Mean", "Mode", "Standard Deviation"] },
  { q: "The most frequent value in a dataset is the:", correct: "Mode", wrong: ["Mean", "Median", "Average"] },
  { q: "The difference between the highest and lowest values is the:", correct: "Range", wrong: ["Mean", "Standard Deviation", "Variance"] },
  { q: "The process of hiding details within a data set to protect privacy is:", correct: "Anonymization", wrong: ["Cleansing", "Encryption", "Compression"] },
  { q: "A person who uses their skills to gain unauthorized access to data is a:", correct: "Hacker", wrong: ["Programmer", "SysAdmin", "Data Scientist"] },
  { q: "A hacker who identifies security flaws to help fix them is a:", correct: "White Hat Hacker", wrong: ["Black Hat Hacker", "Gray Hat Hacker", "Script Kiddie"] },
  { q: "A hacker who breaks into systems for malicious reasons is a:", correct: "Black Hat Hacker", wrong: ["White Hat Hacker", "Ethical Hacker", "Security Researcher"] },
  { q: "A 'Smart Home' is part of the:", correct: "Internet of Things (IoT)", wrong: ["Distributed Network", "Parallel System", "Closed Network"] },
  { q: "Which of the following is NOT a data visualization tool?", correct: "Router", wrong: ["Tableau", "Excel", "Google Charts"] },
  { q: "The speed of parallel computing is limited by:", correct: "The part of the task that cannot be parallelized", wrong: ["The length of the ethernet cable", "The number of users online", "The amount of metadata"] },
  { q: "The total number of calculations a parallel system can do per second is its:", correct: "Throughput", wrong: ["Latency", "Bandwidth", "Scalability"] },
  { q: "Which of the following is an example of 'Open Data'?", correct: "Weather data provided by the government", wrong: ["Your private medical records", "A company's secret recipe", "Your bank statement"] },
  { q: "True or False: Deleting a post on social media means it is gone forever from the internet.", correct: "False", wrong: ["True"] },
  { q: "Which of the following is a common source of 'Dirty Data'?", correct: "User entry errors and duplicate records", wrong: ["High-speed fiber optics", "Lossless compression", "Binary encoding"] },
  { q: "The 'Privacy Paradox' refers to:", correct: "People saying they value privacy but giving it up for convenience", wrong: ["Computers being both fast and slow", "Passwords being hard to remember", "The internet being both public and private"] },
  { q: "A data visualization that shows changes over time is usually a:", correct: "Line Graph", wrong: ["Pie Chart", "Scatter Plot", "Map"] },
  { q: "The process of verifying that a user is who they say they are is:", correct: "Authentication", wrong: ["Authorization", "Encryption", "Anonymization"] },
  { q: "The process of determining what a user is allowed to do is:", correct: "Authorization", wrong: ["Authentication", "Encryption", "Registration"] },
  { q: "An 'Exploit' is:", correct: "A piece of software that takes advantage of a security flaw", wrong: ["A type of data visualization", "A high-speed router", "A programming language"] },
  { q: "A 'Zero-Day' vulnerability is one that:", correct: "Is unknown to the software creator and has no patch", wrong: ["Has been fixed for zero days", "Is only found on day zero of a project", "Causes the computer to reset to zero"] },
  { q: "What is the main advantage of using a database over a spreadsheet for Big Data?", correct: "Better scalability and ability to handle complex relationships", wrong: ["It is easier to make pretty charts", "It uses more memory", "It doesn't require a password"] },
  { q: "Which of the following is an ethical concern of facial recognition?", correct: "Misidentification of minorities and lack of consent", wrong: ["Higher resolution cameras", "Faster processing speeds", "Using too much battery"] },
  { q: "In computer science, 'Bias' usually means:", correct: "Systematic error that results in unfairness", wrong: ["A fast way to search", "A type of encryption", "The physical tilt of a monitor"] },
  { q: "Which is a more secure way to store a password in a database?", correct: "Hashed version", wrong: ["Plain text", "In a spreadsheet", "On a sticky note"] },
  { q: "The term 'Digital Footprint' refers to:", correct: "All the information about a person that exists online", wrong: ["The physical size of a computer", "The speed of someone's typing", "A brand of laptop"] },
  { q: "A 'Patch' is:", correct: "An update to software to fix a bug or security hole", wrong: ["A physical repair to a wire", "A way to compress a file", "A type of data visualization"] },
  { q: "Using computer power to guess every possible password is a:", correct: "Brute Force Attack", wrong: ["Phishing Attack", "DDoS Attack", "Man-in-the-middle"] },
  { q: "Which of the following is a benefit of the 'Open Source' movement?", correct: "Community collaboration and transparency", wrong: ["Guaranteed profit for the author", "Strict secrecy of code", "Lower quality software"] },
  { q: "Which of the following is a PII?", correct: "Fingerprint data", wrong: ["The weather in Chicago", "The number of bits in a byte", "The color of the sky"] },
  { q: "Why do companies collect 'Metadata' about your phone calls?", correct: "To analyze who you talk to and for how long", wrong: ["To listen to the actual conversation", "To record your voice", "To speed up the connection"] },
  { q: "The 'Internet of Things' can pose a security risk because:", correct: "Many devices have weak security and no easy way to update", wrong: ["They use too much electricity", "They are too small to be hacked", "They only use binary"] },
  { q: "A visual that uses geographical locations to show data is a:", correct: "Heat Map (or Choropleth)", wrong: ["Scatter Plot", "Box Plot", "Histogram"] },
  { q: "The 'Long Tail' in data refers to:", correct: "The large number of niche products that sell in small quantities", wrong: ["The time it takes to download a large file", "The physical length of a server rack", "A very long binary number"] },
  { q: "Which of the following is a legal way to use someone else's code?", correct: "Following the terms of its license", wrong: ["Changing the variable names and saying you wrote it", "Copying it from a private repository", "Using it if they didn't put a copyright symbol"] }
    ],

    // Unit 5: Impact of Computing
    // Covers: beneficial/harmful effects, digital divide, bias,
    //         crowdsourcing, legal/ethical concerns, intellectual property.
    5: [
{ q: "The use of computers to simulate human intelligence is:", correct: "Artificial Intelligence", wrong: ["Distributed Computing", "Quantum Computing", "Automation"] },
  { q: "The practice of using software to perform tasks that were previously done by humans is:", correct: "Automation", wrong: ["Collaboration", "Encryption", "Decomposition"] },
  { q: "A digital currency in which encryption techniques regulate the generation of units is:", correct: "Cryptocurrency", wrong: ["E-commerce", "Digital Wallet", "Credit"] },
  { q: "A decentralized, distributed ledger technology that records transactions is:", correct: "Blockchain", wrong: ["SQL Database", "Cloud Storage", "Centralized Ledger"] },
  { q: "The moral principles that govern the use of computers are:", correct: "Computer Ethics", wrong: ["Computer Logic", "Computer Law", "Digital Protocols"] },
  { q: "The unequal distribution of technology and internet access is the:", correct: "Digital Divide", wrong: ["Bandwidth Gap", "Scalability Error", "Net Neutrality"] },
  { q: "Which of the following is a positive impact of social media?", correct: "Global connectivity and rapid information sharing", wrong: ["Echo chambers", "Cyberbullying", "Spread of misinformation"] },
  { q: "The phenomenon where people are only exposed to information that supports their existing beliefs is an:", correct: "Echo Chamber", wrong: ["Encryption Tunnel", "Open Forum", "Digital Archive"] },
  { q: "False or misleading information spread intentionally is:", correct: "Disinformation", wrong: ["Misinformation", "Metadata", "Open Data"] },
  { q: "Information that is false but spread without malicious intent is:", correct: "Misinformation", wrong: ["Disinformation", "Fact", "Propaganda"] },
  { q: "Using computer systems to monitor people's activities is:", correct: "Surveillance", wrong: ["Sampling", "Filtering", "Mining"] },
  { q: "The ability of a person to use technology to participate in society is:", correct: "Digital Literacy", wrong: ["Digital Fluency", "Coding", "Hardware Knowledge"] },
  { q: "The concept that internet service providers should treat all data equally is:", correct: "Net Neutrality", wrong: ["Digital Divide", "Open Access", "Public Domain"] },
  { q: "Which of the following is an environmental impact of computing?", correct: "Electronic waste (e-waste) and high energy consumption", wrong: ["Improved air quality", "Less use of sand", "Reduced noise pollution"] },
  { q: "The practice of moving a job from a human worker to a machine is:", correct: "Job Displacement", wrong: ["Job Enhancement", "Automation", "Job Outsourcing"] },
  { q: "Which of the following is a way to bridge the digital divide?", correct: "Providing low-cost internet and devices to underserved areas", wrong: ["Increasing the price of smartphones", "Building more fiber optics in wealthy cities", "Censoring the internet"] },
  { q: "The use of technology to make a political or social statement is:", correct: "Hacktivism", wrong: ["Cyberterrorism", "Digital Marketing", "Phishing"] },
  { q: "The process of verifying a person's identity using physical traits (fingerprints, face) is:", correct: "Biometrics", wrong: ["Cryptography", "Phonetics", "Demographics"] },
  { q: "The ability of a computer to learn from data without being explicitly programmed is:", correct: "Machine Learning", wrong: ["Hardcoding", "Linear Search", "Logical Deduction"] },
  { q: "The use of technology to improve the lives of people with disabilities is:", correct: "Assistive Technology", wrong: ["Automation", "Artificial Intelligence", "Adaptive Design"] },
  { q: "A 'Smart City' uses technology to:", correct: "Improve efficiency, reduce waste, and enhance residents' lives", wrong: ["Control everyone's thoughts", "Only allow rich people to live there", "Eliminate all cars"] },
  { q: "The study of how humans interact with computers is:", correct: "Human-Computer Interaction (HCI)", wrong: ["Sociology", "Psychology", "Ergonomics"] },
  { q: "Ensuring that a website can be used by people with visual or hearing impairments is:", correct: "Web Accessibility", wrong: ["Web Design", "Search Engine Optimization", "Net Neutrality"] },
  { q: "Which of the following is an example of an 'Ethical Dilemma' in computing?", correct: "Programming self-driving cars to make life-and-death decisions", wrong: ["Choosing between Python and Java", "Buying a new laptop", "Deleting an old file"] },
  { q: "The 'Gig Economy' is powered by apps that connect:", correct: "Freelance workers with short-term tasks", wrong: ["Large corporations with permanent employees", "Students with teachers", "Governments with citizens"] },
  { q: "Which technology allows for high-speed, low-latency mobile internet?", correct: "5G", wrong: ["4G", "WiFi", "Bluetooth"] },
  { q: "The practice of using 'Fake News' to influence an election is a risk to:", correct: "Democracy", wrong: ["Encryption", "The CPU", "Bandwidth"] },
  { q: "The set of rights a person has over the things they create is:", correct: "Intellectual Property", wrong: ["Real Estate", "Metadata", "Digital Citizenship"] },
  { q: "A 'Patent' protects:", correct: "Inventions and functional designs", wrong: ["Books and music", "Logos and brand names", "Short slogans"] },
  { q: "A 'Trademark' protects:", correct: "Logos, brand names, and slogans", wrong: ["Inventions", "Source code", "Movies"] },
  { q: "The use of computer power to mine cryptocurrency consumes:", correct: "Significant amounts of electricity", wrong: ["Almost no energy", "Only solar power", "Binary data"] },
  { q: "Which of the following is a benefit of telecommuting (working from home)?", correct: "Reduced traffic congestion and flexible hours", wrong: ["Increased social isolation", "Higher office costs", "Slower communication"] },
  { q: "A 'Deepfake' is:", correct: "An AI-generated video or image that looks real but is fake", wrong: ["A very old photo", "A high-resolution movie", "An encrypted file"] },
  { q: "The practice of attacking a nation's infrastructure through computers is:", correct: "Cyberwarfare", wrong: ["Cybercrime", "Phishing", "Spamming"] },
  { q: "Which of the following is an example of an 'Algorithmic Bias' in hiring?", correct: "An AI filtering out resumes from women because it was trained on male data", wrong: ["A computer sorting resumes by years of experience", "A human manager picking a candidate they like", "An online test checking for math skills"] },
  { q: "The 'Internet of Things' can help the environment by:", correct: "Optimizing energy use in smart grids and buildings", wrong: ["Producing more plastic", "Using more batteries", "Encouraging people to buy more gadgets"] },
  { q: "What is 'Crowdsourcing' used for in science?", correct: "Allowing thousands of people to help analyze data or images", wrong: ["Buying more lab equipment", "Hiding results from the public", "Paying one expert a lot of money"] },
  { q: "The ability to access information from anywhere at any time is:", correct: "Ubiquitous Computing", wrong: ["Parallel Computing", "Local Computing", "Sequential Computing"] },
  { q: "Which of the following is an example of 'E-waste'?", correct: "An old smartphone or broken monitor", wrong: ["A digital file", "A spam email", "Binary code"] },
  { q: "A digital system that tracks your every move and gives you a score is a:", correct: "Social Credit System", wrong: ["Credit Card", "Digital Wallet", "Blockchain"] },
  { q: "The use of computers to create 3D physical objects is:", correct: "3D Printing (Additive Manufacturing)", wrong: ["Laser Cutting", "Digital Rendering", "Modeling"] },
  { q: "Which of the following is a risk of relying on 'Cloud Storage'?", correct: "Loss of control over data and dependence on internet access", wrong: ["Unlimited space", "Automatic backups", "Lower costs"] },
  { q: "A 'Smart Contract' is a:", correct: "Self-executing contract with the terms written into code on a blockchain", wrong: ["Contract signed with a digital pen", "Legal document about AI", "A password-protected file"] },
  { q: "Which technology is used to create a simulated environment that you can interact with?", correct: "Virtual Reality (VR)", wrong: ["Augmented Reality (AR)", "Artificial Intelligence", "High-Definition Video"] },
  { q: "Which technology overlays digital information onto the real world?", correct: "Augmented Reality (AR)", wrong: ["Virtual Reality", "Blockchain", "Encryption"] },
  { q: "The 'filter bubble' is created by:", correct: "Algorithms that only show you content you already like", wrong: ["A physical screen protector", "A virus that deletes emails", "A firewall"] },
  { q: "True or False: Information on the internet is always permanent.", correct: "False (it can be deleted, but it's difficult)", wrong: ["True"] },
  { q: "Which of the following is a way to protect your 'Digital Identity'?", correct: "Being careful about what you post and checking privacy settings", wrong: ["Sharing your password with friends", "Using your real name for everything", "Never updating your software"] },
  { q: "An 'online' community of people with shared interests is a:", correct: "Social Network", wrong: ["LAN", "Botnet", "Database"] },
  { q: "The use of computers to steal money or personal info is:", correct: "Cybercrime", wrong: ["Computer Science", "Programming", "Automation"] },
  { q: "A person who is 'digitally native' is someone who:", correct: "Grew up in an era where digital technology was always present", wrong: ["Was born in Silicon Valley", "Knows how to build a computer", "Only uses paper"] },
  { q: "Which of the following is an ethical concern of 'Big Data' in healthcare?", correct: "Who owns the data and how it might affect insurance rates", wrong: ["Faster diagnosis of diseases", "Improved medical research", "Better patient care"] },
  { q: "The term for when technology advances so fast that it changes human life fundamentally is:", correct: "The Singularity", wrong: ["The Big Bang", "The Industrial Revolution", "The Digital Age"] },
  { q: "Which of the following is a benefit of 'Open Access' research journals?", correct: "Information is available to everyone for free, accelerating discovery", wrong: ["Authors make more money", "Information is kept secret", "Lower quality of papers"] },
  { q: "The practice of 'Sharenting' refers to:", correct: "Parents sharing a lot of information about their children online", wrong: ["Sharing a Netflix account", "Renting a car with an app", "Dividing a hard drive into parts"] },
  { q: "Which technology allows computers to process data using 'qubits'?", correct: "Quantum Computing", wrong: ["Binary Computing", "Parallel Computing", "Cloud Computing"] },
  { q: "The 'right to repair' movement advocates for:", correct: "The ability for consumers to fix their own electronic devices", wrong: ["The right to get a new phone every year", "The right to free internet", "The right to return broken items"] },
  { q: "Which of the following is a risk of 'facial recognition' in public spaces?", correct: "Constant surveillance and loss of anonymity", wrong: ["Faster entry to buildings", "Improved security in airports", "Automatic tagging in photos"] },
  { q: "A 'Dark Web' is a part of the internet that:", correct: "Is hidden from search engines and requires special software to access", wrong: ["Is only accessible at night", "Contains only encrypted files", "Is owned by the government"] },
  { q: "Which of the following is a social impact of the 'Internet of Things'?", correct: "Increased convenience but potential for remote hacking of homes", wrong: ["More people reading books", "Less use of electricity", "Elimination of all privacy"] },
  { q: "The use of algorithms to determine who gets a loan or is hired is:", correct: "Automated Decision-Making", wrong: ["Human Resources", "Manual Review", "Crowdsourcing"] },
  { q: "Which of the following is a benefit of 'Biometric' security?", correct: "You can't forget your 'password' (your fingerprint)", wrong: ["It can be easily changed if hacked", "It works for everyone in the world", "It is 100% accurate"] },
  { q: "Which technology is most likely to disrupt the banking industry?", correct: "Blockchain and Cryptocurrency", wrong: ["5G", "Artificial Intelligence", "3D Printing"] },
  { q: "The 'Digital Citizenship' refers to:", correct: "The responsible and ethical use of technology", wrong: ["Having an online passport", "Voting via a smartphone", "Paying for high-speed internet"] },
  { q: "Which of the following is a common theme in computer ethics?", correct: "Respect for privacy and intellectual property", wrong: ["Speed over accuracy", "Making the most money", "Hacking for fun"] },
  { q: "The use of computers in 'Precision Agriculture' helps farmers by:", correct: "Using sensors and data to optimize water and fertilizer use", wrong: ["Making the crops grow in binary", "Allowing them to work less", "Eliminating the need for sun"] },
  { q: "Which of the following is a potential negative impact of 'Simulation' software?", correct: "Users might over-rely on a model that doesn't reflect reality", wrong: ["Saving lives in medical training", "Predicting the weather", "Reducing the cost of experiments"] },
  { q: "Which technology is used to ensure a digital file is unique and cannot be copied (e.g., digital art)?", correct: "NFT (Non-Fungible Token)", wrong: ["JPEG", "Blockchain", "Bitcoin"] },
  { q: "The 'CISA' (Cybersecurity and Infrastructure Security Agency) is a:", correct: "Government agency that helps protect US infrastructure from cyber threats", wrong: ["Company that makes antivirus software", "A group of hackers", "A type of firewall"] },
  { q: "Which of the following is a way to reduce your 'Environmental Footprint' in computing?", correct: "Recycling old devices and using energy-efficient hardware", wrong: ["Buying a new phone every 6 months", "Leaving your computer on 24/7", "Deleting all your files"] },
  { q: "What is the primary concern of 'Net Neutrality' advocates?", correct: "ISPs might block or slow down content from competitors", wrong: ["The internet might run out of IP addresses", "Viruses might spread faster", "Cables might break"] },
  { q: "The 'Turing Test' is used to measure:", correct: "Whether a computer can exhibit behavior indistinguishable from a human", wrong: ["How fast a computer can solve an algorithm", "The bandwidth of a network", "The security of a password"] },
  { q: "Which of the following is an example of 'Crowdsourcing' a map?", correct: "Waze or OpenStreetMap", wrong: ["Google Maps", "A paper map", "A GPS satellite"] },
  { q: "The 'Gopher' protocol was an early alternative to:", correct: "The World Wide Web (HTTP)", wrong: ["Email (SMTP)", "File Transfer (FTP)", "Binary"] },
  { q: "A 'Smart Grid' is an example of computing impacting:", correct: "The energy and utility industry", wrong: ["The gaming industry", "The fashion industry", "The music industry"] }
    ],
};
