// ============================================================
// AP Psychology Question Bank — College Board Units 1-5
// Paste your questions into each unit array below.
// Format matches apush.js: { q, correct, wrong: [a, b, c] }
// ============================================================

const APPSYCH_QUESTIONS = {

    // Unit 1: Biological Bases of Behavior
    // Covers: genetics, heredity, the nervous system, brain structure,
    //         neurotransmitters, sensation, and perception.
    1: [
  { q: "Which part of the neuron receives incoming signals from other neurons?", correct: "Dendrites", wrong: ["Axon", "Soma", "Myelin Sheath"] },
  { q: "The fatty substance that insulates the axon and speeds up neural impulses is called:", correct: "Myelin Sheath", wrong: ["Glial cells", "Terminal buttons", "Synaptic vesicles"] },
  { q: "A brief electrical charge that travels down an axon is known as the:", correct: "Action Potential", wrong: ["Resting potential", "Threshold", "Refractory period"] },
  { q: "Which neurotransmitter is most closely linked to reward, movement, and learning?", correct: "Dopamine", wrong: ["Serotonin", "Acetylcholine", "GABA"] },
  { q: "An undersupply of which neurotransmitter is most linked to depression?", correct: "Serotonin", wrong: ["Glutamate", "Norepinephrine", "Endorphins"] },
  { q: "The 'All-or-None' Law states that a neuron either fires at full strength or:", correct: "Does not fire at all", wrong: ["Fires at half strength", "Fires slowly", "Fires only partially"] },
  { q: "Which division of the nervous system is responsible for the 'Fight or Flight' response?", correct: "Sympathetic Nervous System", wrong: ["Parasympathetic", "Somatic", "Central"] },
  { q: "The Master Gland of the endocrine system is the:", correct: "Pituitary Gland", wrong: ["Adrenal Gland", "Thyroid", "Pancreas"] },
  { q: "Which brain structure acts as the sensory switchboard for all senses except smell?", correct: "Thalamus", wrong: ["Hypothalamus", "Hippocampus", "Amygdala"] },
  { q: "The amygdala is primarily involved in the processing of:", correct: "Emotion, especially fear and aggression", wrong: ["Memory formation", "Body temperature", "Visual information"] },
  { q: "If a person has difficulty forming new memories, which structure is likely damaged?", correct: "Hippocampus", wrong: ["Pons", "Medulla", "Cerebellum"] },
  { q: "Which lobe of the brain contains the primary visual cortex?", correct: "Occipital Lobe", wrong: ["Frontal", "Parietal", "Temporal"] },
  { q: "The Broca’s Area is responsible for:", correct: "Speech production", wrong: ["Language comprehension", "Hearing", "Spatial reasoning"] },
  { q: "Wernicke’s Area is primarily located in which lobe?", correct: "Temporal Lobe", wrong: ["Frontal", "Occipital", "Parietal"] },
  { q: "The 'Split-Brain' procedure involves severing which structure?", correct: "Corpus Callosum", wrong: ["Brainstem", "Thalamus", "Optic Chiasm"] },
  { q: "Phineas Gage’s personality change was due to damage in his:", correct: "Frontal Lobe", wrong: ["Motor cortex", "Parietal lobe", "Cerebellum"] },
  { q: "The space between two neurons where communication occurs is the:", correct: "Synapse", wrong: ["Node of Ranvier", "Axon hillock", "Reuptake site"] },
  { q: "Which chemical acts as a natural painkiller in the body?", correct: "Endorphins", wrong: ["GABA", "Glutamate", "Epinephrine"] },
  { q: "The reabsorption of a neurotransmitter by the sending neuron is called:", correct: "Reuptake", wrong: ["Depolarization", "Hyperpolarization", "Agonism"] },
  { q: "Which tool uses magnetic fields and radio waves to produce computer-generated images of soft tissue?", correct: "MRI", wrong: ["EEG", "PET scan", "CT scan"] },
  { q: "The cerebellum is most important for:", correct: "Balance and coordination", wrong: ["Heart rate", "Sleep cycles", "Logical thinking"] },
  { q: "Which part of the brainstem controls heartbeat and breathing?", correct: "Medulla", wrong: ["Pons", "Reticular Formation", "Midbrain"] },
  { q: "Agonists are chemicals that:", correct: "Mimic the effects of a neurotransmitter", wrong: ["Block neurotransmitters", "Destroy neurotransmitters", "Store neurotransmitters"] },
  { q: "The proportion of variation among individuals that we can attribute to genes is called:", correct: "Heritability", wrong: ["Adaptation", "Epigenetics", "Mutation"] },
  { q: "Plasticity refers to the brain's ability to:", correct: "Reorganize after damage or build new pathways", wrong: ["Produce new neurons daily", "Maintain a constant temperature", "Stop neural firing"] },
  { q: "The somatosensory cortex is located in the:", correct: "Parietal Lobe", wrong: ["Frontal Lobe", "Temporal Lobe", "Occipital Lobe"] },
  { q: "Circadian rhythm refers to:", correct: "A 24-hour biological clock", wrong: ["The 90-minute sleep cycle", "Seasonal affective disorder", "Rapid eye movement"] },
  { q: "During which stage of sleep do vivid dreams typically occur?", correct: "REM", wrong: ["NREM-1", "NREM-2", "NREM-3"] },
  { q: "The tendency for the brain's two hemispheres to specialize in certain functions is:", correct: "Lateralization", wrong: ["Neurogenesis", "Long-term potentiation", "Synaptic pruning"] },
  { q: "The 'Rest and Digest' system is formally known as the:", correct: "Parasympathetic Nervous System", wrong: ["Sympathetic", "Peripheral", "Endocrine"] },
  { q: "The threadlike structures made of DNA molecules that contain the genes are:", correct: "Chromosomes", wrong: ["Proteins", "Neurons", "Hormones"] },
  { q: "Which scanning technique measures glucose consumption in the brain?", correct: "PET scan", wrong: ["EEG", "fMRI", "X-ray"] },
  { q: "Sleep spindles occur in which stage of sleep?", correct: "NREM-2", wrong: ["NREM-1", "NREM-3", "REM"] },
  { q: "Which neurotransmitter is the primary inhibitory messenger?", correct: "GABA", wrong: ["Glutamate", "Dopamine", "Acetylcholine"] },
  { q: "Which neurotransmitter is the primary excitatory messenger?", correct: "Glutamate", wrong: ["Serotonin", "GABA", "Endorphins"] },
  { q: "Interneurons are found exclusively in the:", correct: "Central Nervous System", wrong: ["Peripheral Nervous System", "Endocrine System", "Somatic System"] },
  { q: "The depletion of Acetylcholine (ACh) is associated with:", correct: "Alzheimer’s Disease", wrong: ["Parkinson’s Disease", "Schizophrenia", "Multiple Sclerosis"] },
  { q: "Hormones are chemical messengers of the:", correct: "Endocrine System", wrong: ["Nervous System", "Skeletal System", "Digestive System"] },
  { q: "The Reticular Formation is primarily responsible for:", correct: "Arousal and alertness", wrong: ["Hunger", "Memory", "Vision"] },
  { q: "The Hypothalamus influences the 'Four Fs': Fighting, Fleeing, Feeding, and:", correct: "Fornication (Sexual behavior)", wrong: ["Feeling", "Focusing", "Filtering"] },
  { q: "Fraternal twins are also known as:", correct: "Dizygotic", wrong: ["Monozygotic", "Genotypes", "Phenotypes"] },
  { q: "The physical expression of a genetic code is the:", correct: "Phenotype", wrong: ["Genotype", "Allele", "Mutation"] },
  { q: "A 'Antagonist' drug works by:", correct: "Blocking a receptor site", wrong: ["Mimicking a neurotransmitter", "Increasing reuptake", "Repairing axons"] },
  { q: "Which lobe is responsible for executive functions and planning?", correct: "Frontal Lobe", wrong: ["Parietal", "Temporal", "Occipital"] },
  { q: "Damage to the motor cortex in the left hemisphere would affect:", correct: "Movement on the right side of the body", wrong: ["Movement on the left side", "Vision in the left eye", "Hearing in both ears"] },
  { q: "Which gland triggers the release of adrenaline and noradrenaline?", correct: "Adrenal Glands", wrong: ["Pineal Gland", "Pituitary Gland", "Thyroid"] },
  { q: "The study of the evolution of behavior and the mind is:", correct: "Evolutionary Psychology", wrong: ["Behaviorism", "Humanism", "Psychobiology"] },
  { q: "Neurogenesis refers to the:", correct: "Formation of new neurons", wrong: ["Death of neurons", "Speed of neural travel", "Mapping of the brain"] },
  { q: "Individuals with 'Prosopagnosia' cannot:", correct: "Recognize faces", wrong: ["Speak clearly", "Walk straight", "Read text"] },
  { q: "Which brain structure regulates thirst and body temperature?", correct: "Hypothalamus", wrong: ["Thalamus", "Amygdala", "Pons"] },
  { q: "Afferent neurons are also called:", correct: "Sensory neurons", wrong: ["Motor neurons", "Interneurons", "Glial cells"] },
  { q: "Efferent neurons are also called:", correct: "Motor neurons", wrong: ["Sensory neurons", "Interneurons", "Inhibitory neurons"] },
  { q: "What is the standard resting potential of a neuron?", correct: "-70 mV", wrong: ["0 mV", "+40 mV", "-100 mV"] },
  { q: "The Pineal gland secretes which sleep-inducing hormone?", correct: "Melatonin", wrong: ["Cortisol", "Insulin", "Oxytocin"] },
  { q: "What is the 'Master Clock' located in the hypothalamus?", correct: "Suprachiasmatic Nucleus (SCN)", wrong: ["Basal Ganglia", "Substantia Nigra", "Ventral Tegmental Area"] },
  { q: "NREM-3 sleep is also known as:", correct: "Deep Sleep (Delta waves)", wrong: ["Light sleep", "Paradoxical sleep", "Dream sleep"] },
  { q: "Paradoxical sleep is another name for:", correct: "REM sleep", wrong: ["NREM-1", "Stage 4", "Alpha sleep"] },
  { q: "A person whose brain cannot produce enough GABA might suffer from:", correct: "Seizures or Insomnia", wrong: ["Depression", "Memory loss", "Muscle paralysis"] },
  { q: "What is the effect of Curare on the body?", correct: "It blocks ACh receptors, causing paralysis", wrong: ["It mimics Dopamine", "It increases Serotonin", "It triggers the sympathetic system"] },
  { q: "The 'Gate-Control' theory explains the regulation of:", correct: "Pain", wrong: ["Vision", "Hunger", "Thirst"] },
  { q: "Which part of the neuron contains the nucleus?", correct: "Soma", wrong: ["Axon", "Myelin", "Dendrite"] },
  { q: "Neural communication is a(n) ________ process.", correct: "Electrochemical", wrong: ["Purely electrical", "Purely chemical", "Mechanical"] },
  { q: "Refractory period is the time when:", correct: "A neuron cannot fire again until it resets", wrong: ["A neuron is resting", "A neuron is growing", "Neurotransmitters are released"] },
  { q: "Identical twins originate from:", correct: "A single fertilized egg that splits", wrong: ["Two separate eggs", "Two separate sperm", "The same placenta but different eggs"] },
  { q: "Epigenetics studies how environment triggers:", correct: "Gene expression", wrong: ["Genetic mutations", "Chromosomal deletion", "DNA sequencing"] },
  { q: "Which neurotransmitter is involved in muscle action and memory?", correct: "Acetylcholine", wrong: ["GABA", "Dopamine", "Glutamate"] },
  { q: "The 'Reward Center' of the brain is often associated with the:", correct: "Hypothalamus", wrong: ["Cerebellum", "Medulla", "Pons"] },
  { q: "Which area helps us coordinate our left and right hand movements?", correct: "Corpus Callosum", wrong: ["Thalamus", "Amygdala", "Pituitary"] },
  { q: "Mirror neurons are believed to be the basis for:", correct: "Empathy and imitation", wrong: ["Sleep apnea", "Synesthesia", "Blindness"] },
  { q: "If the reticular formation is severed, what usually results?", correct: "A coma", wrong: ["Inability to speak", "Blindness", "Loss of appetite"] },
  { q: "What brain wave is associated with being awake and alert?", correct: "Beta waves", wrong: ["Alpha waves", "Delta waves", "Theta waves"] },
  { q: "What brain wave is associated with relaxed wakefulness?", correct: "Alpha waves", wrong: ["Delta waves", "Beta waves", "Gamma waves"] },
  { q: "Which disorder is characterized by a lack of the neurotransmitter Orexin?", correct: "Narcolepsy", wrong: ["Insomnia", "Sleep Apnea", "Night Terrors"] },
  { q: "The 'Old Brain' refers to the brainstem and:", correct: "Limbic System", wrong: ["Cerebral Cortex", "Frontal Lobe", "Neocortex"] },
    ],

    2: [
  { q: "The process of getting information into the memory system is called:", correct: "Encoding", wrong: ["Storage", "Retrieval", "Rehearsal"] },
  { q: "The retention of encoded information over time is:", correct: "Storage", wrong: ["Encoding", "Retrieval", "Chunking"] },
  { q: "The process of getting information out of memory storage is:", correct: "Retrieval", wrong: ["Encoding", "Decoding", "Consolidation"] },
  { q: "A momentary sensory memory of visual stimuli is called:", correct: "Iconic Memory", wrong: ["Echoic Memory", "Implicit Memory", "Working Memory"] },
  { q: "A momentary sensory memory of auditory stimuli is called:", correct: "Echoic Memory", wrong: ["Iconic Memory", "Flashbulb Memory", "Tactile Memory"] },
  { q: "Organizing items into familiar, manageable units to increase memory capacity is:", correct: "Chunking", wrong: ["Mnemonics", "Spacing", "Hierarchy"] },
  { q: "Memory of facts and experiences that one can consciously know and 'declare' is:", correct: "Explicit Memory", wrong: ["Implicit Memory", "Procedural Memory", "Echoic Memory"] },
  { q: "Retention independent of conscious recollection, such as riding a bike, is:", correct: "Implicit Memory", wrong: ["Explicit Memory", "Declarative Memory", "Semantic Memory"] },
  { q: "Our tendency to recall best the last and first items in a list is known as:", correct: "Serial Position Effect", wrong: ["Spacing Effect", "Testing Effect", "Next-in-line Effect"] },
  { q: "A clear memory of an emotionally significant moment or event is a:", correct: "Flashbulb Memory", wrong: ["Sensory Memory", "Short-term Memory", "Procedural Memory"] },
  { q: "The neural center in the limbic system that helps process explicit memories for storage is the:", correct: "Hippocampus", wrong: ["Cerebellum", "Basal Ganglia", "Amygdala"] },
  { q: "The brain structure responsible for storing implicit/procedural memories is the:", correct: "Cerebellum", wrong: ["Hippocampus", "Thalamus", "Frontal Lobe"] },
  { q: "Disruptive effect of prior learning on the recall of new information is:", correct: "Proactive Interference", wrong: ["Retroactive Interference", "Anterograde Amnesia", "Retrograde Amnesia"] },
  { q: "Disruptive effect of new learning on the recall of old information is:", correct: "Retroactive Interference", wrong: ["Proactive Interference", "Source Amnesia", "Repression"] },
  { q: "An inability to form new memories after a brain injury is:", correct: "Anterograde Amnesia", wrong: ["Retrograde Amnesia", "Infantile Amnesia", "Source Amnesia"] },
  { q: "An inability to retrieve information from one's past is:", correct: "Retrograde Amnesia", wrong: ["Anterograde Amnesia", "Motivated Forgetting", "Misinformation Effect"] },
  { q: "Incorporating misleading information into one's memory of an event is the:", correct: "Misinformation Effect", wrong: ["Source Amnesia", "Deja Vu", "Reconsolidation"] },
  { q: "A mental grouping of similar objects, events, ideas, or people is a:", correct: "Concept", wrong: ["Prototype", "Algorithm", "Heuristic"] },
  { q: "A mental image or best example of a category is a:", correct: "Prototype", wrong: ["Concept", "Schema", "Heuristic"] },
  { q: "A methodical, logical rule or procedure that guarantees solving a particular problem is an:", correct: "Algorithm", wrong: ["Heuristic", "Insight", "Intuition"] },
  { q: "A simple thinking strategy that often allows us to make judgments and solve problems efficiently is a:", correct: "Heuristic", wrong: ["Algorithm", "Fixation", "Confirmation Bias"] },
  { q: "A sudden realization of a problem's solution is called:", correct: "Insight", wrong: ["Algorithm", "Heuristic", "Trial and Error"] },
  { q: "Tendency to search for information that supports our preconceptions and ignore contradictory evidence is:", correct: "Confirmation Bias", wrong: ["Belief Perseverance", "Availability Heuristic", "Overconfidence"] },
  { q: "The inability to see a problem from a fresh perspective is:", correct: "Fixation", wrong: ["Insight", "Mental Set", "Functional Fixedness"] },
  { q: "A tendency to approach a problem in one particular way, often a way that has been successful in the past, is a:", correct: "Mental Set", wrong: ["Prototype", "Insight", "Algorithm"] },
  { q: "Estimating the likelihood of events based on their availability in memory is the:", correct: "Availability Heuristic", wrong: ["Representativeness Heuristic", "Anchoring Bias", "Hindsight Bias"] },
  { q: "Judging the likelihood of things in terms of how well they seem to match particular prototypes is the:", correct: "Representativeness Heuristic", wrong: ["Availability Heuristic", "Confirmation Bias", "Framing"] },
  { q: "The way an issue is posed or presented, which can significantly affect decisions and judgments, is:", correct: "Framing", wrong: ["Priming", "Anchoring", "Rehearsal"] },
  { q: "The smallest distinctive sound unit in language is a:", correct: "Phoneme", wrong: ["Morpheme", "Grammar", "Syntax"] },
  { q: "The smallest unit that carries meaning in a language is a:", correct: "Morpheme", wrong: ["Phoneme", "Syllable", "Lexicon"] },
  { q: "The system of rules for combining words into grammatically sensible sentences is:", correct: "Syntax", wrong: ["Semantics", "Phonology", "Pragmatics"] },
  { q: "The stage of speech development in which the infant utters various sounds at 4 months is the:", correct: "Babbling Stage", wrong: ["One-word Stage", "Two-word Stage", "Telegraphic Speech"] },
  { q: "Early speech stage in which a child speaks like a telegram using nouns and verbs is:", correct: "Telegraphic Speech", wrong: ["Babbling", "One-word Stage", "Holophrastic Stage"] },
  { q: "Whorf's hypothesis that language determines the way we think is:", correct: "Linguistic Determinism", wrong: ["Universal Grammar", "Language Acquisition Device", "Critical Period"] },
  { q: "Mental quality consisting of the ability to learn from experience and solve problems is:", correct: "Intelligence", wrong: ["Cognition", "Wisdom", "Aptitude"] },
  { q: "Charles Spearman believed we have one __________ underlying all intelligent behavior.", correct: "g factor (General Intelligence)", wrong: ["Multiple Intelligences", "Triarchic Theory", "Emotional Intelligence"] },
  { q: "Howard Gardner is known for the theory of:", correct: "Multiple Intelligences", wrong: ["General Intelligence", "Triarchic Theory", "Fluid Intelligence"] },
  { q: "Robert Sternberg's three intelligences include Analytical, Creative, and:", correct: "Practical", wrong: ["Emotional", "Social", "Linguistic"] },
  { q: "The ability to perceive, understand, manage, and use emotions is:", correct: "Emotional Intelligence", wrong: ["Social Intelligence", "Self-Actualization", "Temperament"] },
  { q: "A test designed to predict a person's future performance or capacity to learn is an:", correct: "Aptitude Test", wrong: ["Achievement Test", "Intelligence Test", "Personality Test"] },
  { q: "A test designed to assess what a person has learned is an:", correct: "Achievement Test", wrong: ["Aptitude Test", "Projective Test", "Reliability Test"] },
  { q: "Defining uniform testing procedures and meaningful scores by comparison with a pretested group is:", correct: "Standardization", wrong: ["Reliability", "Validity", "Normalization"] },
  { q: "The extent to which a test yields consistent results over time is its:", correct: "Reliability", wrong: ["Validity", "Standardization", "Accuracy"] },
  { q: "The extent to which a test measures or predicts what it is supposed to is its:", correct: "Validity", wrong: ["Reliability", "Objectivity", "Standardization"] },
  { q: "Our accumulated knowledge and verbal skills, which increase with age, is:", correct: "Crystallized Intelligence", wrong: ["Fluid Intelligence", "Practical Intelligence", "Creative Intelligence"] },
  { q: "Our ability to reason speedily and abstractly, which decreases in late adulthood, is:", correct: "Fluid Intelligence", wrong: ["Crystallized Intelligence", "General Intelligence", "Emotional Intelligence"] },
  { q: "A self-confirming concern that one will be evaluated based on a negative stereotype is:", correct: "Stereotype Threat", wrong: ["Self-fulfilling Prophecy", "Confirmation Bias", "Hindsight Bias"] },
  { q: "The conscious repetition of information to maintain it in consciousness or encode it is:", correct: "Rehearsal", wrong: ["Retrieval", "Priming", "Interference"] },
  { q: "The activation, often unconsciously, of particular associations in memory is:", correct: "Priming", wrong: ["Framing", "Chunking", "Rehearsal"] },
  { q: "Memory aids that use vivid imagery and organizational devices are:", correct: "Mnemonics", wrong: ["Prototypes", "Heuristics", "Algorithms"] },
  { q: "The tendency to recall experiences that are consistent with one's current good or bad mood is:", correct: "Mood-congruent Memory", wrong: ["State-dependent Memory", "Context-dependent Memory", "Flashbulb Memory"] },
  { q: "The 'magical number' of short-term memory capacity identified by George Miller is:", correct: "7 (plus or minus 2)", wrong: ["5 (plus or minus 1)", "10 (plus or minus 2)", "3 (plus or minus 1)"] },
  { q: "Attributing to the wrong source an event we have experienced, heard about, or read about is:", correct: "Source Amnesia", wrong: ["Misinformation Effect", "Retrograde Amnesia", "Proactive Interference"] },
  { q: "The set of rules by which we derive meaning from morphemes, words, and sentences is:", correct: "Semantics", wrong: ["Syntax", "Grammar", "Phonemes"] },
  { q: "Who proposed the 'Language Acquisition Device' (LAD) and Universal Grammar?", correct: "Noam Chomsky", wrong: ["B.F. Skinner", "Benjamin Whorf", "Jean Piaget"] },
  { q: "Intelligence scores have risen steadily over the 20th century; this is known as the:", correct: "Flynn Effect", wrong: ["Barnum Effect", "Hawthorne Effect", "Placebo Effect"] },
  { q: "A person who is limited in mental ability but has an exceptional specific skill is a:", correct: "Savant", wrong: ["Genius", "Prodigy", "Intellectual Disability"] },
  { q: "Testing a test's reliability by giving the same test to the same people at different times is:", correct: "Test-retest Reliability", wrong: ["Split-half Reliability", "Content Validity", "Predictive Validity"] },
  { q: "Ebbinghaus's 'Forgetting Curve' shows that forgetting is initially ________, then levels off.", correct: "Rapid", wrong: ["Slow", "Constant", "Linear"] },
  { q: "Memory of general knowledge and facts (like the capital of France) is:", correct: "Semantic Memory", wrong: ["Episodic Memory", "Implicit Memory", "Procedural Memory"] },
  { q: "Memory of specific personal events or 'episodes' in one's life is:", correct: "Episodic Memory", wrong: ["Semantic Memory", "Echoic Memory", "Short-term Memory"] },
  { q: "A cognitive bias where a person's first impression of someone influences their overall feelings is the:", correct: "Halo Effect", wrong: ["Framing", "Priming", "Anchoring"] },
  { q: "The tendency to cling to one's initial beliefs even after they have been discredited is:", correct: "Belief Perseverance", wrong: ["Confirmation Bias", "Hindsight Bias", "Overconfidence"] },
  { q: "A tendency to overestimate the accuracy of our beliefs and judgments is:", correct: "Overconfidence", wrong: ["Belief Perseverance", "Self-serving Bias", "Availability Heuristic"] },
  { q: "Developing a memory through the use of meaning and deep processing is:", correct: "Elaborative Rehearsal", wrong: ["Maintenance Rehearsal", "Chunking", "Serial Position"] },
  { q: "A strategy for solving a problem by trying different solutions until one works is:", correct: "Trial and Error", wrong: ["Algorithm", "Heuristic", "Insight"] },
  { q: "The brain area that acts as a 'loading dock' for explicit memories before they go to long-term storage:", correct: "Hippocampus", wrong: ["Amygdala", "Medulla", "Cerebellum"] },
  { q: "The increased efficiency of potential neural firing after brief, rapid stimulation is:", correct: "Long-term Potentiation (LTP)", wrong: ["Neurogenesis", "Synaptic Pruning", "Reuptake"] },
  { q: "Thinking that is intended to find the single best solution to a problem is:", correct: "Convergent Thinking", wrong: ["Divergent Thinking", "Creative Thinking", "Intuition"] },
  { q: "Expanding the number of possible problem solutions; creative thinking that branches out is:", correct: "Divergent Thinking", wrong: ["Convergent Thinking", "Logic", "Functional Fixedness"] },
  { q: "A condition in which people with IQs below 70 have difficulty adapting to life demands is:", correct: "Intellectual Disability", wrong: ["Savant Syndrome", "Giftedness", "Dyslexia"] },
  { q: "The 'Eerie' feeling that 'I've experienced this before' is:", correct: "Deja Vu", wrong: ["Source Amnesia", "Priming", "Flashbulb Memory"] },
  { q: "The theory that we forget because the memory trace physically fades over time is:", correct: "Decay Theory", wrong: ["Interference Theory", "Motivated Forgetting", "Repression"] },
  { q: "Retrieving information by identifying it from a list (e.g., a multiple-choice test) is:", correct: "Recognition", wrong: ["Recall", "Relearning", "Rehearsal"] },
  { q: "Retrieving information learned earlier (e.g., a fill-in-the-blank test) is:", correct: "Recall", wrong: ["Recognition", "Priming", "Spacing"] }
    ],


    3: [
{ q: "A type of learning in which one learns to link two or more stimuli and anticipate events is:", correct: "Classical Conditioning", wrong: ["Operant Conditioning", "Observational Learning", "Insight Learning"] },
  { q: "In classical conditioning, the unlearned, naturally occurring response is the:", correct: "Unconditioned Response (UR)", wrong: ["Conditioned Response", "Neutral Stimulus", "Conditioned Stimulus"] },
  { q: "A stimulus that elicits no response before conditioning is a(n):", correct: "Neutral Stimulus (NS)", wrong: ["Unconditioned Stimulus", "Conditioned Stimulus", "Reinforcer"] },
  { q: "An originally irrelevant stimulus that, after association with a US, triggers a conditioned response is the:", correct: "Conditioned Stimulus (CS)", wrong: ["Unconditioned Stimulus", "Neutral Stimulus", "Primary Reinforcer"] },
  { q: "The initial stage in classical conditioning when one links a neutral stimulus and an unconditioned stimulus is:", correct: "Acquisition", wrong: ["Extinction", "Spontaneous Recovery", "Generalization"] },
  { q: "The diminishing of a conditioned response when the unconditioned stimulus does not follow the CS is:", correct: "Extinction", wrong: ["Acquisition", "Discrimination", "Generalization"] },
  { q: "The reappearance, after a pause, of an extinguished conditioned response is:", correct: "Spontaneous Recovery", wrong: ["Acquisition", "Extinction", "Discrimination"] },
  { q: "The tendency for stimuli similar to the conditioned stimulus to elicit similar responses is:", correct: "Generalization", wrong: ["Discrimination", "Extinction", "Shaping"] },
  { q: "The learned ability to distinguish between a conditioned stimulus and other irrelevant stimuli is:", correct: "Discrimination", wrong: ["Generalization", "Acquisition", "Spontaneous Recovery"] },
  { q: "In operant conditioning, any event that strengthens the behavior it follows is a:", correct: "Reinforcer", wrong: ["Punishment", "Neutral Stimulus", "Conditioned Stimulus"] },
  { q: "An operant conditioning procedure in which reinforcers guide behavior toward closer approximations of the goal is:", correct: "Shaping", wrong: ["Classical Conditioning", "Modeling", "Extinction"] },
  { q: "Increasing behaviors by presenting a pleasurable stimulus after a response is:", correct: "Positive Reinforcement", wrong: ["Negative Reinforcement", "Positive Punishment", "Negative Punishment"] },
  { q: "Increasing behaviors by stopping or reducing negative stimuli is:", correct: "Negative Reinforcement", wrong: ["Positive Reinforcement", "Positive Punishment", "Negative Punishment"] },
  { q: "An innately reinforcing stimulus, such as one that satisfies a biological need (e.g., food), is a:", correct: "Primary Reinforcer", wrong: ["Secondary Reinforcer", "Conditioned Reinforcer", "Negative Reinforcer"] },
  { q: "A stimulus that gains its reinforcing power through its association with a primary reinforcer is a:", correct: "Secondary Reinforcer", wrong: ["Primary Reinforcer", "Punishment", "Unconditioned Stimulus"] },
  { q: "Reinforcing a response every time it occurs is:", correct: "Continuous Reinforcement", wrong: ["Partial Reinforcement", "Fixed-Ratio", "Variable-Interval"] },
  { q: "A reinforcement schedule that reinforces a response after a specified number of responses is:", correct: "Fixed-Ratio", wrong: ["Variable-Ratio", "Fixed-Interval", "Variable-Interval"] },
  { q: "A reinforcement schedule that reinforces a response after an unpredictable number of responses is:", correct: "Variable-Ratio", wrong: ["Fixed-Ratio", "Fixed-Interval", "Variable-Interval"] },
  { q: "A reinforcement schedule that reinforces a response after a specified time has elapsed is:", correct: "Fixed-Interval", wrong: ["Fixed-Ratio", "Variable-Ratio", "Variable-Interval"] },
  { q: "An event that tends to decrease the behavior that it follows is:", correct: "Punishment", wrong: ["Reinforcement", "Conditioning", "Modeling"] },
  { q: "Learning by observing others is called:", correct: "Observational Learning", wrong: ["Classical Conditioning", "Operant Conditioning", "Latent Learning"] },
  { q: "The process of observing and imitating a specific behavior is:", correct: "Modeling", wrong: ["Shaping", "Discrimination", "Reinforcement"] },
  { q: "Who conducted the famous 'Bobo Doll' experiment on observational learning?", correct: "Albert Bandura", wrong: ["B.F. Skinner", "Ivan Pavlov", "John Watson"] },
  { q: "Learning that occurs but is not apparent until there is an incentive to demonstrate it is:", correct: "Latent Learning", wrong: ["Insight Learning", "Operant Conditioning", "Classical Conditioning"] },
  { q: "A mental representation of the layout of one's environment is a:", correct: "Cognitive Map", wrong: ["Heuristic", "Prototype", "Schema"] },
  { q: "Thorndike's principle that behaviors followed by favorable consequences become more likely is the:", correct: "Law of Effect", wrong: ["Principle of Reinforcement", "Law of Association", "Conditioning Rule"] },
  { q: "A biological predisposition to learn associations that have survival value is:", correct: "Preparedness", wrong: ["Instinctive Drift", "Latent Learning", "Shaping"] },
  { q: "Biological growth processes that enable orderly changes in behavior, relatively uninfluenced by experience, is:", correct: "Maturation", wrong: ["Learning", "Socialization", "Habituation"] },
  { q: "All the mental activities associated with thinking, knowing, remembering, and communicating is:", correct: "Cognition", wrong: ["Development", "Learning", "Perception"] },
  { q: "A concept or framework that organizes and interprets information is a:", correct: "Schema", wrong: ["Prototype", "Heuristic", "Accommodation"] },
  { q: "Interpreting our new experiences in terms of our existing schemas is:", correct: "Assimilation", wrong: ["Accommodation", "Conservation", "Maturation"] },
  { q: "Adapting our current understandings (schemas) to incorporate new information is:", correct: "Accommodation", wrong: ["Assimilation", "Object Permanence", "Egocentrism"] },
  { q: "The awareness that things continue to exist even when not perceived is:", correct: "Object Permanence", wrong: ["Conservation", "Egocentrism", "Theory of Mind"] },
  { q: "Piaget's stage (birth to 2 years) where infants know the world in terms of sensory impressions is:", correct: "Sensorimotor", wrong: ["Preoperational", "Concrete Operational", "Formal Operational"] },
  { q: "The principle that properties such as mass and volume remain the same despite changes in form is:", correct: "Conservation", wrong: ["Object Permanence", "Assimilation", "Egocentrism"] },
  { q: "Piaget's stage (2 to 7 years) where a child learns to use language but does not yet comprehend logic is:", correct: "Preoperational", wrong: ["Sensorimotor", "Concrete Operational", "Formal Operational"] },
  { q: "The difficulty of a preoperational child to take another's point of view is:", correct: "Egocentrism", wrong: ["Conservation", "Theory of Mind", "Object Permanence"] },
  { q: "People's ideas about their own and others' mental states is:", correct: "Theory of Mind", wrong: ["Egocentrism", "Self-concept", "Schema"] },
  { q: "Piaget's stage (7 to 11 years) where children gain mental operations to think logically about events is:", correct: "Concrete Operational", wrong: ["Preoperational", "Sensorimotor", "Formal Operational"] },
  { q: "Piaget's stage (age 12+) where people begin to think logically about abstract concepts is:", correct: "Formal Operational", wrong: ["Concrete Operational", "Preoperational", "Sensorimotor"] },
  { q: "An emotional tie with another person is:", correct: "Attachment", wrong: ["Imprinting", "Socialization", "Temperament"] },
  { q: "An optimal period early in life when exposure to certain stimuli produces normal development is a:", correct: "Critical Period", wrong: ["Sensitive Period", "Window of Opportunity", "Maturation Phase"] },
  { q: "The process by which certain animals form strong attachments during a critical period is:", correct: "Imprinting", wrong: ["Attachment", "Modeling", "Assimilation"] },
  { q: "A person's characteristic emotional reactivity and intensity is their:", correct: "Temperament", wrong: ["Personality", "Self-concept", "Attachment Style"] },
  { q: "Kohlberg's level of moral thinking focused on self-interest and avoiding punishment is:", correct: "Preconventional", wrong: ["Conventional", "Postconventional", "Unconventional"] },
  { q: "Kohlberg's level of moral thinking focused on upholding laws and social rules is:", correct: "Conventional", wrong: ["Preconventional", "Postconventional", "Ethical"] },
  { q: "Kohlberg's level of moral thinking focused on self-defined ethical principles is:", correct: "Postconventional", wrong: ["Preconventional", "Conventional", "Legalistic"] },
  { q: "Erikson's stage for infancy (0-1 year) where basic needs must be met by caregivers is:", correct: "Trust vs. Mistrust", wrong: ["Autonomy vs. Shame", "Initiative vs. Guilt", "Identity vs. Confusion"] },
  { q: "Erikson's stage for adolescence where the task is to solidify a sense of self is:", correct: "Identity vs. Role Confusion", wrong: ["Intimacy vs. Isolation", "Generativity vs. Stagnation", "Industry vs. Inferiority"] },
  { q: "Erikson's stage for young adulthood where the task is to form close relationships is:", correct: "Intimacy vs. Isolation", wrong: ["Identity vs. Role Confusion", "Integrity vs. Despair", "Generativity vs. Stagnation"] },
  { q: "Erikson's stage for late adulthood where one looks back on life with satisfaction or regret is:", correct: "Integrity vs. Despair", wrong: ["Generativity vs. Stagnation", "Trust vs. Mistrust", "Intimacy vs. Isolation"] },
  { q: "The socially influenced characteristics by which people define boy, girl, man, and woman is:", correct: "Gender", wrong: ["Sex", "Gender Identity", "Gender Role"] },
  { q: "A set of expected behaviors for males or for females is a:", correct: "Gender Role", wrong: ["Gender Identity", "Gender Typing", "Social Script"] },
  { q: "Our sense of being male, female, or some combination of the two is our:", correct: "Gender Identity", wrong: ["Gender Role", "Gender Typing", "Sexual Orientation"] },
  { q: "Any physical or verbal behavior intended to harm someone physically or emotionally is:", correct: "Aggression", wrong: ["Hostility", "Punishment", "Negative Reinforcement"] },
  { q: "The 'Little Albert' experiment demonstrated that ________ can be conditioned.", correct: "Fear", wrong: ["Hunger", "Happiness", "Anger"] },
  { q: "The use of 'tokens' (like stickers or fake coins) that can be traded for rewards is a:", correct: "Token Economy", wrong: ["Fixed-ratio Schedule", "Secondary Reinforcement", "Shaping Program"] },
  { q: "A behaviorist who believed that all behavior is the result of reinforcement and punishment:", correct: "B.F. Skinner", wrong: ["Sigmund Freud", "Carl Rogers", "Abraham Maslow"] },
  { q: "The philosopher who believed infants are a 'Tabula Rasa' (blank slate):", correct: "John Locke", wrong: ["Jean-Jacques Rousseau", "Plato", "René Descartes"] },
  { q: "Harry Harlow's monkey studies showed that ________ was more important than food for attachment.", correct: "Contact Comfort", wrong: ["Security", "Strictness", "Independence"] },
  { q: "Parenting style that is demanding but also responsive to the child's needs is:", correct: "Authoritative", wrong: ["Authoritarian", "Permissive", "Uninvolved"] },
  { q: "Parenting style that imposes strict rules and expects blind obedience is:", correct: "Authoritarian", wrong: ["Authoritative", "Permissive", "Negligent"] },
  { q: "Parenting style where parents submit to children's desires and use little punishment is:", correct: "Permissive", wrong: ["Authoritative", "Authoritarian", "Democratic"] },
  { q: "Decreasing responsiveness with repeated stimulation is:", correct: "Habituation", wrong: ["Sensitization", "Extinction", "Adaptation"] },
  { q: "Agents, such as chemicals and viruses, that can reach the embryo or fetus and cause harm are:", correct: "Teratogens", wrong: ["Pathogens", "Antigens", "Mutagens"] },
  { q: "Physical and cognitive abnormalities in children caused by a pregnant woman's heavy drinking is:", correct: "Fetal Alcohol Syndrome (FAS)", wrong: ["Down Syndrome", "Fragile X Syndrome", "Failure to Thrive"] },
  { q: "The period from conception to 2 weeks is the stage of the:", correct: "Zygote", wrong: ["Embryo", "Fetus", "Neonate"] },
  { q: "The period from 2 weeks through 8 weeks is the stage of the:", correct: "Embryo", wrong: ["Zygote", "Fetus", "Infant"] },
  { q: "The period from 9 weeks until birth is the stage of the:", correct: "Fetus", wrong: ["Embryo", "Zygote", "Placenta"] },
  { q: "Vygotsky's term for the range of tasks a child can perform with help but not yet alone is:", correct: "Zone of Proximal Development (ZPD)", wrong: ["Scaffolding", "Assimilation", "Conservation"] },
  { q: "A baby's tendency, when touched on the cheek, to turn toward the touch and open the mouth is:", correct: "Rooting Reflex", wrong: ["Moro Reflex", "Babinski Reflex", "Sucking Reflex"] },
  { q: "The first menstrual period in girls is called:", correct: "Menarche", wrong: ["Menopause", "Puberty", "Spermarche"] },
  { q: "The culturally preferred timing of social events such as marriage and retirement is the:", correct: "Social Clock", wrong: ["Biological Clock", "Life Cycle", "Maturity Gauge"] },
  { q: "Mary Ainsworth's procedure to measure attachment styles is known as the:", correct: "Strange Situation", wrong: ["Visual Cliff", "Bobo Doll Study", "Skinner Box"] },
  { q: "The tendency of repetitive behaviors to lead to the same outcome is known as:", correct: "Instinctive Drift", wrong: ["Shaping", "Latent Learning", "Maturation"] }
    ],

    // Unit 4: Social Psychology and Personality
    // Covers: social influence, conformity, obedience, group dynamics,
    //         attribution, attitudes, personality theories (Freud, trait, humanistic).
    4: [
{ q: "The theory that we explain someone's behavior by crediting either the situation or the person's disposition is:", correct: "Attribution Theory", wrong: ["Cognitive Dissonance", "Social Facilitation", "Self-Serving Bias"] },
  { q: "The tendency for observers to underestimate the impact of the situation and overestimate the impact of personal disposition is:", correct: "Fundamental Attribution Error", wrong: ["Self-Fulfilling Prophecy", "Confirmation Bias", "Just-World Phenomenon"] },
  { q: "The theory that we act to reduce the discomfort we feel when two of our thoughts are inconsistent is:", correct: "Cognitive Dissonance Theory", wrong: ["Social Exchange Theory", "Reciprocity Norm", "Drive-Reduction Theory"] },
  { q: "Adjusting our behavior or thinking to coincide with a group standard is:", correct: "Conformity", wrong: ["Obedience", "Social Loafing", "Groupthink"] },
  { q: "Solomon Asch is best known for his studies on:", correct: "Conformity", wrong: ["Obedience", "Attachment", "Cognitive Development"] },
  { q: "Stanley Milgram's famous experiments investigated the nature of:", correct: "Obedience", wrong: ["Conformity", "Altruism", "Bystander Intervention"] },
  { q: "Improved performance on simple or well-learned tasks in the presence of others is:", correct: "Social Facilitation", wrong: ["Social Loafing", "Group Polarization", "Deindividuation"] },
  { q: "The tendency for people in a group to exert less effort when pooling their efforts toward a common goal is:", correct: "Social Loafing", wrong: ["Social Facilitation", "Bystander Effect", "Deindividuation"] },
  { q: "The loss of self-awareness and self-restraint occurring in group situations that foster arousal and anonymity is:", correct: "Deindividuation", wrong: ["Groupthink", "Conformity", "Social Loafing"] },
  { q: "The enhancement of a group's prevailing inclinations through discussion within the group is:", correct: "Group Polarization", wrong: ["Groupthink", "Social Facilitation", "Deindividuation"] },
  { q: "The mode of thinking that occurs when the desire for harmony in a decision-making group overrides a realistic appraisal of alternatives is:", correct: "Groupthink", wrong: ["Group Polarization", "Social Loafing", "Conformity"] },
  { q: "An unjustifiable (and usually negative) attitude toward a group and its members is:", correct: "Prejudice", wrong: ["Discrimination", "Stereotyping", "Ingroup Bias"] },
  { q: "Generalized (sometimes accurate but often overgeneralized) beliefs about a group of people are:", correct: "Stereotypes", wrong: ["Prejudices", "Discriminations", "Attributions"] },
  { q: "Unjustifiable negative behavior toward a group and its members is:", correct: "Discrimination", wrong: ["Prejudice", "Stereotyping", "Scapegoating"] },
  { q: "The tendency to favor our own group is:", correct: "Ingroup Bias", wrong: ["Outgroup Homogeneity", "Scapegoating", "Self-Serving Bias"] },
  { q: "The theory that prejudice offers an outlet for anger by providing someone to blame is:", correct: "Scapegoat Theory", wrong: ["Just-World Theory", "Social Exchange Theory", "Frustration-Aggression Principle"] },
  { q: "The tendency to believe that the world is fair and that people therefore get what they deserve and deserve what they get is:", correct: "Just-World Phenomenon", wrong: ["Hindsight Bias", "Self-Serving Bias", "Fundamental Attribution Error"] },
  { q: "The principle that frustration—the blocking of an attempt to achieve some goal—creates anger, which can generate aggression is:", correct: "Frustration-Aggression Principle", wrong: ["Catharsis Hypothesis", "Social Learning Theory", "Reciprocity Norm"] },
  { q: "The phenomenon that repeated exposure to novel stimuli increases liking of them is:", correct: "Mere Exposure Effect", wrong: ["Halo Effect", "Matching Hypothesis", "Self-Disclosure"] },
  { q: "Unselfish regard for the welfare of others is:", correct: "Altruism", wrong: ["Empathy", "Reciprocity", "Equity"] },
  { q: "The tendency for any given bystander to be less likely to give aid if other bystanders are present is:", correct: "Bystander Effect", wrong: ["Social Loafing", "Diffusion of Responsibility", "Deindividuation"] },
  { q: "The theory that our social behavior is an exchange process, the aim of which is to maximize benefits and minimize costs is:", correct: "Social Exchange Theory", wrong: ["Reciprocity Norm", "Social-Responsibility Norm", "Equity Theory"] },
  { q: "Shared goals that override differences among people and require their cooperation are:", correct: "Superordinate Goals", wrong: ["Individualistic Goals", "Competitive Goals", "Social Traps"] },
  { q: "According to Freud, the part of personality that represents internalized ideals and provides standards for judgment is the:", correct: "Superego", wrong: ["Id", "Ego", "Libido"] },
  { q: "According to Freud, the unconscious psychic energy that strives to satisfy basic sexual and aggressive drives is the:", correct: "Id", wrong: ["Ego", "Superego", "Collective Unconscious"] },
  { q: "The largely conscious 'executive' part of personality that mediates between the id and superego is the:", correct: "Ego", wrong: ["Self", "Persona", "Superego"] },
  { q: "The ego's protective methods of reducing anxiety by unconsciously distorting reality are:", correct: "Defense Mechanisms", wrong: ["Fixations", "Projective Tests", "Free Associations"] },
  { q: "Banishing anxiety-arousing thoughts, feelings, and memories from consciousness is:", correct: "Repression", wrong: ["Regression", "Projection", "Reaction Formation"] },
  { q: "Retreating to a more infantile psychosexual stage, where some psychic energy remains fixated, is:", correct: "Regression", wrong: ["Repression", "Rationalization", "Displacement"] },
  { q: "Switching unacceptable impulses into their opposites is:", correct: "Reaction Formation", wrong: ["Projection", "Rationalization", "Sublimation"] },
  { q: "Disguising one's own threatening impulses by attributing them to others is:", correct: "Projection", wrong: ["Displacement", "Reaction Formation", "Repression"] },
  { q: "Offering self-justifying explanations in place of the real, more threatening unconscious reasons for one's actions is:", correct: "Rationalization", wrong: ["Denial", "Sublimation", "Projection"] },
  { q: "Shifting sexual or aggressive impulses toward a more acceptable or less threatening object or person is:", correct: "Displacement", wrong: ["Sublimation", "Reaction Formation", "Projection"] },
  { q: "Refusing to believe or even perceive painful realities is:", correct: "Denial", wrong: ["Repression", "Rationalization", "Fixation"] },
  { q: "Carl Jung's concept of a shared, inherited reservoir of memory traces from our species' history is the:", correct: "Collective Unconscious", wrong: ["Personal Unconscious", "Archetype", "Inferiority Complex"] },
  { q: "A personality test, such as the Rorschach, that provides ambiguous stimuli designed to trigger projection of one's inner dynamics is a:", correct: "Projective Test", wrong: ["Personality Inventory", "Objective Test", "Aptitude Test"] },
  { q: "According to Maslow, the ultimate psychological need that arises after basic physical and psychological needs are met is:", correct: "Self-Actualization", wrong: ["Self-Esteem", "Unconditional Positive Regard", "Belongingness"] },
  { q: "According to Carl Rogers, an attitude of total acceptance toward another person is:", correct: "Unconditional Positive Regard", wrong: ["Empathy", "Congruence", "Genuineness"] },
  { q: "A characteristic pattern of behavior or a disposition to feel and act is a:", correct: "Trait", wrong: ["Type", "Self-Concept", "Factor"] },
  { q: "Which 'Big Five' trait refers to being organized, careful, and disciplined?", correct: "Conscientiousness", wrong: ["Agreeableness", "Neuroticism", "Openness"] },
  { q: "Which 'Big Five' trait refers to emotional instability, anxiety, and insecurity?", correct: "Neuroticism", wrong: ["Extraversion", "Conscientiousness", "Openness"] },
  { q: "The interacting influences of behavior, internal cognition, and environment is:", correct: "Reciprocal Determinism", wrong: ["Social-Cognitive Perspective", "Self-Efficacy", "External Locus of Control"] },
  { q: "Our sense of competence and effectiveness on a specific task is our:", correct: "Self-Efficacy", wrong: ["Self-Esteem", "Self-Concept", "Locus of Control"] },
  { q: "The tendency to perceive oneself favorably is:", correct: "Self-Serving Bias", wrong: ["Narcissism", "Self-Efficacy", "Hindsight Bias"] },
  { q: "Overestimating others' noticing and evaluating our appearance and performance is the:", correct: "Spotlight Effect", wrong: ["Halo Effect", "Transparency Effect", "Self-Consciousness Bias"] },
  { q: "A readiness to perceive oneself favorably is:", correct: "Self-Serving Bias", wrong: ["Confirmation Bias", "Self-Concept", "Individualism"] },
  { q: "Giving priority to one's own goals over group goals and defining one's identity in terms of personal attributes is:", correct: "Individualism", wrong: ["Collectivism", "Narcissism", "Self-Actualization"] },
  { q: "Giving priority to the goals of one's group and defining one's identity accordingly is:", correct: "Collectivism", wrong: ["Individualism", "Altruism", "Conformity"] },
  { q: "The perception that one controls one's own fate is an:", correct: "Internal Locus of Control", wrong: ["External Locus of Control", "Self-Efficacy", "Learned Helplessness"] },
  { q: "The perception that chance or outside forces beyond our personal control determine our fate is an:", correct: "External Locus of Control", wrong: ["Internal Locus of Control", "Self-Serving Bias", "Reciprocal Determinism"] },
  { q: "The hopelessness and passive resignation an animal or human learns when unable to avoid repeated aversive events is:", correct: "Learned Helplessness", wrong: ["Depression", "Fixation", "External Locus of Control"] },
  { q: "The process by which children incorporate their parents' values into their developing superegos is:", correct: "Identification", wrong: ["Internalization", "Modeling", "Fixation"] },
  { q: "A lingering focus of pleasure-seeking energies at an earlier psychosexual stage is:", correct: "Fixation", wrong: ["Regression", "Repression", "Complex"] },
  { q: "Alfred Adler's concept of a person's feelings of lack of worth and strategy to overcome these feelings is the:", correct: "Inferiority Complex", wrong: ["Oedipus Complex", "Superego", "Fixation"] },
  { q: "The most widely used projective test, a set of 10 inkblots, was designed by:", correct: "Hermann Rorschach", wrong: ["Henry Murray", "Sigmund Freud", "Carl Jung"] },
  { q: "Hans and Sybil Eysenck focused on which two dimensions of personality?", correct: "Extraversion-Introversion and Emotional Stability-Instability", wrong: ["Conscientiousness and Agreeableness", "Masculinity and Femininity", "Thinking and Feeling"] },
  { q: "A questionnaire on which people respond to items designed to gauge a wide range of feelings and behaviors is a:", correct: "Personality Inventory", wrong: ["Projective Test", "Free Association", "Clinical Interview"] },
  { q: "The most widely researched and clinically used of all personality tests is the:", correct: "MMPI", wrong: ["TAT", "Rorschach", "Myers-Briggs"] },
  { q: "The hopelessness and passive resignation we learn when unable to avoid repeated bad events is:", correct: "Learned Helplessness", wrong: ["Locus of Control", "Self-Efficacy", "External Motivation"] },
  { q: "The expectation that you will be able to perform a certain task successfully is:", correct: "Self-Efficacy", wrong: ["Self-Esteem", "Self-Serving Bias", "Self-Concept"] },
  { q: "Our all-encompassing central nervous system of personality, our thoughts and feelings about ourselves, is our:", correct: "Self-Concept", wrong: ["Self-Esteem", "Ego", "Ideal Self"] },
  { q: "Social influence resulting from a person's desire to gain approval or avoid disapproval is:", correct: "Normative Social Influence", wrong: ["Informational Social Influence", "Conformity", "Obedience"] },
  { q: "Social influence resulting from one's willingness to accept others' opinions about reality is:", correct: "Informational Social Influence", wrong: ["Normative Social Influence", "Groupthink", "Persuasion"] },
  { q: "A situation in which the conflicting parties, by each rationally pursuing their self-interest, become caught in mutually destructive behavior is a:", correct: "Social Trap", wrong: ["Prisoner's Dilemma", "Mirror-Image Perception", "Self-Fulfilling Prophecy"] },
  { q: "The deep affectionate attachment we feel for those with whom our lives are intertwined is:", correct: "Companionate Love", wrong: ["Passionate Love", "Altruism", "Equity"] },
  { q: "An aroused state of intense positive absorption in another, usually present at the beginning of a love relationship, is:", correct: "Passionate Love", wrong: ["Companionate Love", "Intimacy", "Commitment"] },
  { q: "A condition in which people receive from a relationship in proportion to what they give to it is:", correct: "Equity", wrong: ["Self-Disclosure", "Altruism", "Social Exchange"] },
  { q: "The expectation that people will help, not hurt, those who have helped them is the:", correct: "Reciprocity Norm", wrong: ["Social-Responsibility Norm", "Social Exchange Theory", "Bystander Effect"] },
  { q: "The expectation that people will help those needing their help is the:", correct: "Social-Responsibility Norm", wrong: ["Reciprocity Norm", "Altruism", "Equity"] },
  { q: "Mutual views often held by conflicting people, as when each side sees itself as ethical and peaceful and views the other side as evil and aggressive is:", correct: "Mirror-Image Perceptions", wrong: ["Self-Fulfilling Prophecies", "Group Polarization", "Fundamental Attribution Error"] },
  { q: "A belief that leads to its own fulfillment is a:", correct: "Self-Fulfilling Prophecy", wrong: ["Stereotype Threat", "Hindsight Bias", "Confirmation Bias"] },
  { q: "The tendency to overestimate the extent to which others share our beliefs and behaviors is the:", correct: "False Consensus Effect", wrong: ["Self-Serving Bias", "Spotlight Effect", "Confirmation Bias"] },
  { q: "The use of 'graduated and reciprocated initiatives in tension-reduction' to decrease international tensions is:", correct: "GRIT", wrong: ["NATO", "Superordinate Goals", "Social Exchange"] },
  { q: "Changing one's behavior in response to a direct request is:", correct: "Compliance", wrong: ["Conformity", "Obedience", "Social Facilitation"] },
  { q: "The theory that we view ourselves as a member of a social group and use that to shape our identity is:", correct: "Social Identity Theory", wrong: ["Self-Concept Theory", "Individualism", "Group Polarization"] }
    ],

    // Unit 5: Mental and Physical Health
    // Covers: psychological disorders (DSM categories), treatment approaches,
    //         stress, coping, health psychology, and well-being.
    5: [
{ q: "A syndrome marked by a clinically significant disturbance in an individual's cognition, emotion regulation, or behavior is a:", correct: "Psychological Disorder", wrong: ["Medical Condition", "Maladaptive Behavior", "Personality Trait"] },
  { q: "The concept that diseases, in this case psychological disorders, have physical causes that can be diagnosed and treated is the:", correct: "Medical Model", wrong: ["Biopsychosocial Approach", "DSM-5", "Humanistic Perspective"] },
  { q: "The most common system for classifying psychological disorders is the:", correct: "DSM-5", wrong: ["ICD-10", "MMPI", "TAT"] },
  { q: "An anxiety disorder in which a person is continually tense, apprehensive, and in a state of autonomic nervous system arousal is:", correct: "Generalized Anxiety Disorder", wrong: ["Panic Disorder", "Phobia", "PTSD"] },
  { q: "An anxiety disorder marked by unpredictable, minutes-long episodes of intense dread is:", correct: "Panic Disorder", wrong: ["Generalized Anxiety Disorder", "Agoraphobia", "OCD"] },
  { q: "An anxiety disorder marked by a persistent, irrational fear and avoidance of a specific object, activity, or situation is a:", correct: "Phobia", wrong: ["Panic Attack", "Social Anxiety", "GAD"] },
  { q: "Fear or avoidance of situations, such as crowds or wide open places, where one has felt loss of control and panic is:", correct: "Agoraphobia", wrong: ["Claustrophobia", "Social Anxiety Disorder", "Specific Phobia"] },
  { q: "A disorder characterized by unwanted repetitive thoughts and/or actions is:", correct: "Obsessive-Compulsive Disorder (OCD)", wrong: ["PTSD", "ADHD", "Generalized Anxiety Disorder"] },
  { q: "A disorder characterized by haunting memories, nightmares, social withdrawal, and insomnia after a traumatic experience is:", correct: "Post-Traumatic Stress Disorder (PTSD)", wrong: ["Generalized Anxiety Disorder", "Major Depressive Disorder", "Panic Disorder"] },
  { q: "A disorder in which a person experiences two or more weeks with five or more symptoms, at least one of which must be either depressed mood or loss of interest is:", correct: "Major Depressive Disorder", wrong: ["Persistent Depressive Disorder", "Bipolar Disorder", "Seasonal Affective Disorder"] },
  { q: "A disorder in which a person alternates between the hopelessness and lethargy of depression and the overexcited state of mania is:", correct: "Bipolar Disorder", wrong: ["Major Depressive Disorder", "Schizophrenia", "Cyclothymic Disorder"] },
  { q: "A hyperactive, wildly optimistic state in which dangerously poor judgment is common is:", correct: "Mania", wrong: ["Euphoria", "Psychosis", "Hypomania"] },
  { q: "A psychological disorder characterized by delusions, hallucinations, disorganized speech, and/or diminished, inappropriate emotional expression is:", correct: "Schizophrenia", wrong: ["Dissociative Identity Disorder", "Bipolar Disorder", "Schizoid Personality Disorder"] },
  { q: "False beliefs, often of persecution or grandeur, that may accompany psychotic disorders are:", correct: "Delusions", wrong: ["Hallucinations", "Illusions", "Word Salads"] },
  { q: "False sensory experiences, such as seeing something in the absence of an external visual stimulus, are:", correct: "Hallucinations", wrong: ["Delusions", "Flashes", "Dissociations"] },
  { q: "A disorder in which a person's conscious awareness becomes separated from previous memories, thoughts, and feelings is a:", correct: "Dissociative Disorder", wrong: ["Personality Disorder", "Psychotic Disorder", "Somatoform Disorder"] },
  { q: "A rare dissociative disorder in which a person exhibits two or more distinct and alternating personalities is:", correct: "Dissociative Identity Disorder (DID)", wrong: ["Schizophrenia", "Bipolar Disorder", "Borderline Personality Disorder"] },
  { q: "Inflexible and enduring behavior patterns that impair social functioning are:", correct: "Personality Disorders", wrong: ["Anxiety Disorders", "Mood Disorders", "Dissociative Disorders"] },
  { q: "A personality disorder in which a person (usually a man) exhibits a lack of conscience for wrongdoing, even toward friends and family members is:", correct: "Antisocial Personality Disorder", wrong: ["Borderline Personality Disorder", "Narcissistic Personality Disorder", "Histrionic Personality Disorder"] },
  { q: "An eating disorder in which a person maintains a starvation diet despite being significantly underweight is:", correct: "Anorexia Nervosa", wrong: ["Bulimia Nervosa", "Binge-Eating Disorder", "Orthorexia"] },
  { q: "An eating disorder in which a person alternates binge eating with purging or fasting is:", correct: "Bulimia Nervosa", wrong: ["Anorexia Nervosa", "Binge-Eating Disorder", "Pica"] },
  { q: "Treatment involving psychological techniques; consists of interactions between a trained therapist and someone seeking to overcome psychological difficulties is:", correct: "Psychotherapy", wrong: ["Biomedical Therapy", "Eclectic Approach", "Psychoanalysis"] },
  { q: "Prescribed medications or procedures that act directly on the person's physiology are:", correct: "Biomedical Therapy", wrong: ["Psychotherapy", "Behavioral Therapy", "Cognitive Therapy"] },
  { q: "An approach to psychotherapy that, depending on the client's problems, uses techniques from various forms of therapy is the:", correct: "Eclectic Approach", wrong: ["Integrated Approach", "Humanistic Approach", "Cognitive-Behavioral Approach"] },
  { q: "Sigmund Freud's therapeutic technique that aimed to bring repressed feelings into conscious awareness is:", correct: "Psychoanalysis", wrong: ["Psychodynamic Therapy", "Client-Centered Therapy", "Insight Therapy"] },
  { q: "In psychoanalysis, the blocking from consciousness of anxiety-laden material is:", correct: "Resistance", wrong: ["Transference", "Interpretation", "Repression"] },
  { q: "In psychoanalysis, the patient's transfer to the analyst of emotions linked with other relationships is:", correct: "Transference", wrong: ["Resistance", "Projection", "Displacement"] },
  { q: "Therapy that derives from the psychoanalytic tradition but views individuals as responding to unconscious forces and childhood experiences is:", correct: "Psychodynamic Therapy", wrong: ["Humanistic Therapy", "Behavioral Therapy", "Psychoanalysis"] },
  { q: "A humanistic therapy, developed by Carl Rogers, in which the therapist uses techniques such as active listening within a genuine, accepting, empathic environment is:", correct: "Client-Centered Therapy", wrong: ["Cognitive Therapy", "Gestalt Therapy", "Existential Therapy"] },
  { q: "Empathic listening in which the listener echoes, restates, and clarifies is:", correct: "Active Listening", wrong: ["Reflective Listening", "Free Association", "Interpretation"] },
  { q: "Therapy that applies learning principles to the elimination of unwanted behaviors is:", correct: "Behavior Therapy", wrong: ["Cognitive Therapy", "Humanistic Therapy", "Psychodynamic Therapy"] },
  { q: "Behavior therapy procedures that use classical conditioning to evoke new responses to stimuli that are triggering unwanted behaviors are:", correct: "Counterconditioning", wrong: ["Aversive Conditioning", "Exposure Therapy", "Operant Conditioning"] },
  { q: "Behavioral techniques, such as systematic desensitization, that treat anxieties by exposing people to the things they fear and avoid are:", correct: "Exposure Therapies", wrong: ["Aversive Conditioning", "Client-Centered Therapy", "Psychoanalysis"] },
  { q: "A type of exposure therapy that associates a pleasant relaxed state with gradually increasing anxiety-triggering stimuli is:", correct: "Systematic Desensitization", wrong: ["Aversive Conditioning", "Flooding", "Virtual Reality Exposure"] },
  { q: "A type of counterconditioning that associates an unpleasant state (such as nausea) with an unwanted behavior (such as drinking alcohol) is:", correct: "Aversive Conditioning", wrong: ["Systematic Desensitization", "Token Economy", "Punishment"] },
  { q: "An operant conditioning procedure in which people earn a token for exhibiting a desired behavior and can later exchange the tokens for various privileges or treats is a:", correct: "Token Economy", wrong: ["Shaping Procedure", "Secondary Reinforcement", "Contingency Management"] },
  { q: "Therapy that teaches people new, more adaptive ways of thinking; based on the assumption that thoughts intervene between events and our emotional reactions is:", correct: "Cognitive Therapy", wrong: ["Behavioral Therapy", "Psychoanalysis", "Biomedical Therapy"] },
  { q: "A popular integrative therapy that combines cognitive therapy with behavior therapy is:", correct: "Cognitive-Behavioral Therapy (CBT)", wrong: ["Rational-Emotive Behavior Therapy (REBT)", "Dialectical Behavior Therapy (DBT)", "Insight Therapy"] },
  { q: "Therapy conducted with groups rather than individuals, permitting therapeutic benefits from group interaction is:", correct: "Group Therapy", wrong: ["Family Therapy", "Self-Help Groups", "Couples Therapy"] },
  { q: "The tendency for extreme or unusual scores to fall back toward their average is:", correct: "Regression Toward the Mean", wrong: ["Standardization", "Hindsight Bias", "Normal Curve"] },
  { q: "A procedure for statistically combining the results of many different research studies is:", correct: "Meta-Analysis", wrong: ["Factor Analysis", "Correlation", "Regression"] },
  { q: "Study of the effects of drugs on mind and behavior is:", correct: "Psychopharmacology", wrong: ["Neuropsychology", "Toxicology", "Psychiatry"] },
  { q: "Drugs used to treat schizophrenia and other forms of severe thought disorder are:", correct: "Antipsychotic Drugs", wrong: ["Antianxiety Drugs", "Antidepressant Drugs", "Mood Stabilizers"] },
  { q: "Drugs used to control anxiety and agitation are:", correct: "Antianxiety Drugs", wrong: ["Antipsychotic Drugs", "Antidepressants", "Stimulants"] },
  { q: "Drugs used to treat depression, anxiety disorders, OCD, and PTSD are:", correct: "Antidepressant Drugs", wrong: ["Antianxiety Drugs", "Lithium", "Neuroleptics"] },
  { q: "A biomedical therapy for severely depressed patients in which a brief electric current is sent through the brain of an anesthetized patient is:", correct: "Electroconvulsive Therapy (ECT)", wrong: ["TMS", "Deep Brain Stimulation", "Psychosurgery"] },
  { q: "The application of repeated pulses of magnetic energy to the brain; used to stimulate or suppress brain activity is:", correct: "Transcranial Magnetic Stimulation (TMS)", wrong: ["ECT", "EEG", "fMRI"] },
  { q: "Surgery that removes or destroys brain tissue in an effort to change behavior is:", correct: "Psychosurgery", wrong: ["Lobotomy", "Deep Brain Stimulation", "Neurology"] },
  { q: "A psychosocial surgical procedure once used to calm uncontrollably emotional or violent patients by cutting the nerves connecting the frontal lobes to the emotion-controlling centers of the inner brain is a:", correct: "Lobotomy", wrong: ["Cingulotomy", "Trephination", "Callosotomy"] },
  { q: "Personal strength that helps most people cope with stress and recover from adversity and even trauma is:", correct: "Resilience", wrong: ["Hardiness", "Self-Efficacy", "Post-Traumatic Growth"] },
  { q: "Positive psychological changes as a result of struggling with extremely challenging circumstances and life crises is:", correct: "Post-Traumatic Growth", wrong: ["Resilience", "Sublimation", "Catharsis"] },
  { q: "The study of how psychological, neural, and endocrine processes together affect the immune system and resulting health is:", correct: "Psychoneuroimmunology", wrong: ["Health Psychology", "Behavioral Medicine", "Psychobiology"] },
  { q: "Stress-related physical illness, such as hypertension and some headaches, is a:", correct: "Psychophysiological Illness", wrong: ["Conversion Disorder", "Somatization", "Hypochondriasis"] },
  { q: "Friedman and Rosenman's term for competitive, hard-driving, impatient, verbally aggressive, and anger-prone people is:", correct: "Type A", wrong: ["Type B", "Neurotic", "Introvert"] },
  { q: "Friedman and Rosenman's term for easygoing, relaxed people is:", correct: "Type B", wrong: ["Type A", "Extrovert", "Passive"] },
  { q: "The process by which we perceive and respond to certain events, called stressors, that we appraise as threatening or challenging is:", correct: "Stress", wrong: ["Anxiety", "Conflict", "Pressure"] },
  { q: "Selye's concept of the body's adaptive response to stress in three phases—alarm, resistance, exhaustion—is the:", correct: "General Adaptation Syndrome (GAS)", wrong: ["Stress Response System", "Fight-or-Flight Response", "Transactional Model"] },
  { q: "The clogging of the vessels that nourish the heart muscle; the leading cause of death in many developed countries is:", correct: "Coronary Heart Disease", wrong: ["Hypertension", "Stroke", "Diabetes"] },
  { q: "Alleviating stress using emotional, cognitive, or behavioral methods is:", correct: "Coping", wrong: ["Defense Mechanisms", "Resilience", "Adaptation"] },
  { q: "Attempting to alleviate stress directly by changing the stressor or the way we interact with that stressor is:", correct: "Problem-Focused Coping", wrong: ["Emotion-Focused Coping", "Avoidance Coping", "Mindfulness"] },
  { q: "Attempting to alleviate stress by avoiding or ignoring a stressor and attending to emotional needs related to one's stress reaction is:", correct: "Emotion-Focused Coping", wrong: ["Problem-Focused Coping", "Catharsis", "Denial"] },
  { q: "A system of recording, amplifying, and feeding back information about subtle physiological responses, such as blood pressure or muscle tension is:", correct: "Biofeedback", wrong: ["Neurofeedback", "Meditation", "Relaxation Training"] },
  { q: "Which disorder involves physical symptoms that have no apparent physical cause?", correct: "Somatoform Disorder", wrong: ["Anxiety Disorder", "Dissociative Disorder", "Mood Disorder"] },
  { q: "A somatoform disorder in which a person experiences very specific genuine physical symptoms for which no physiological basis can be found is:", correct: "Conversion Disorder", wrong: ["Hypochondriasis", "Body Dysmorphic Disorder", "Somatization"] },
  { q: "A somatoform disorder in which a person interprets normal physical sensations as symptoms of a disease is:", correct: "Hypochondriasis", wrong: ["Conversion Disorder", "Illness Anxiety Disorder", "Pain Disorder"] },
  { q: "Aaron Beck is most famous for developing therapy for:", correct: "Depression", wrong: ["Schizophrenia", "Phobias", "Personality Disorders"] },
  { q: "Albert Ellis developed which form of cognitive-behavioral therapy?", correct: "Rational-Emotive Behavior Therapy (REBT)", wrong: ["Dialectical Behavior Therapy (DBT)", "Systematic Desensitization", "Aversive Conditioning"] },
  { q: "The use of 'free association' is a core technique in:", correct: "Psychoanalysis", wrong: ["Client-Centered Therapy", "Cognitive Therapy", "Behavioral Therapy"] },
  { q: "Involuntarily smacking of the lips or facial grimacing caused by long-term use of antipsychotic drugs is:", correct: "Tardive Dyskinesia", wrong: ["Akathisia", "Catatonia", "Dystonia"] },
  { q: "Lithium is a chemical element commonly used as a:", correct: "Mood Stabilizer (for Bipolar)", wrong: ["Antidepressant", "Antipsychotic", "Antianxiety Drug"] },
  { q: "The most common hallucination in schizophrenia is:", correct: "Auditory (Voices)", wrong: ["Visual", "Tactile", "Olfactory"] },
  { q: "Negative symptoms of schizophrenia include:", correct: "Flat affect and social withdrawal", wrong: ["Hallucinations and delusions", "Disorganized speech", "Inappropriate laughter"] },
  { q: "Positive symptoms of schizophrenia include:", correct: "Hallucinations and delusions", wrong: ["Flat affect", "Reduced speech", "Lack of motivation"] },
  { q: "A potential biological cause of schizophrenia is an excess of receptors for:", correct: "Dopamine", wrong: ["Serotonin", "GABA", "Acetylcholine"] },
  { q: "A psychological disorder marked by extreme inattention and/or hyperactivity and impulsivity is:", correct: "ADHD", wrong: ["Autism Spectrum Disorder", "Oppositional Defiant Disorder", "Tourette's Syndrome"] }
    ],
};
