// ============================================================
// Standard Trivia Question Bank
// Keyed by OpenTDB category ID so fetchQuestion() can use
// local questions instead of hitting the API every spin.
//
// Category IDs:
//   9  = General Knowledge
//  11  = Entertainment: Film
//  17  = Science & Nature
//  21  = Sports
//  22  = Geography
//  23  = History
//  25  = Art & Literature
//  26  = Celebrities  (not used in wheel — kept for reference)
//
// Format: { q, correct, wrong: [a, b, c] }
// ============================================================

const TRIVIA_QUESTIONS = {

    // ── 9: General Knowledge ─────────────────────────────────
    9: [
        { q:"What is the most spoken language in the world by native speakers?", correct:"Mandarin Chinese", wrong:["English","Spanish","Hindi"] },
        { q:"How many sides does a hexagon have?", correct:"6", wrong:["5","7","8"] },
        { q:"What is the chemical symbol for gold?", correct:"Au", wrong:["Go","Gd","Ag"] },
        { q:"Which planet is known as the Red Planet?", correct:"Mars", wrong:["Venus","Jupiter","Saturn"] },
        { q:"What is the largest ocean on Earth?", correct:"Pacific Ocean", wrong:["Atlantic Ocean","Indian Ocean","Arctic Ocean"] },
        { q:"How many bones are in the adult human body?", correct:"206", wrong:["208","196","212"] },
        { q:"What is the capital of Australia?", correct:"Canberra", wrong:["Sydney","Melbourne","Brisbane"] },
        { q:"Who painted the Mona Lisa?", correct:"Leonardo da Vinci", wrong:["Michelangelo","Raphael","Caravaggio"] },
        { q:"What is the smallest country in the world by area?", correct:"Vatican City", wrong:["Monaco","San Marino","Liechtenstein"] },
        { q:"How many colors are in a rainbow?", correct:"7", wrong:["6","8","5"] },
        { q:"What gas do plants absorb from the atmosphere?", correct:"Carbon dioxide", wrong:["Oxygen","Nitrogen","Hydrogen"] },
        { q:"Which element has the atomic number 1?", correct:"Hydrogen", wrong:["Helium","Lithium","Carbon"] },
        { q:"What is the longest river in the world?", correct:"Nile", wrong:["Amazon","Yangtze","Mississippi"] },
        { q:"In which year did World War II end?", correct:"1945", wrong:["1944","1946","1943"] },
        { q:"What is the hardest natural substance on Earth?", correct:"Diamond", wrong:["Quartz","Corundum","Topaz"] },
        { q:"How many continents are there on Earth?", correct:"7", wrong:["6","5","8"] },
        { q:"What is the currency of Japan?", correct:"Yen", wrong:["Won","Yuan","Ringgit"] },
        { q:"Which animal is known as the 'King of the Jungle'?", correct:"Lion", wrong:["Tiger","Leopard","Cheetah"] },
        { q:"What is the square root of 144?", correct:"12", wrong:["11","13","14"] },
        { q:"Which country has the most natural lakes?", correct:"Canada", wrong:["Russia","USA","Finland"] },
        { q:"What is the tallest mountain in the world?", correct:"Mount Everest", wrong:["K2","Kangchenjunga","Lhotse"] },
        { q:"How many players are on a standard soccer team?", correct:"11", wrong:["10","12","9"] },
        { q:"What is the speed of light (approx.) in km/s?", correct:"300,000", wrong:["150,000","450,000","200,000"] },
        { q:"Which country invented paper?", correct:"China", wrong:["Egypt","India","Mesopotamia"] },
        { q:"What is the most abundant gas in Earth's atmosphere?", correct:"Nitrogen", wrong:["Oxygen","Argon","Carbon dioxide"] },
        { q:"How many teeth does an adult human have (including wisdom teeth)?", correct:"32", wrong:["28","30","34"] },
        { q:"What is the largest desert in the world?", correct:"Antarctic Desert", wrong:["Sahara","Arabian","Gobi"] },
        { q:"Which organ produces insulin?", correct:"Pancreas", wrong:["Liver","Kidney","Spleen"] },
        { q:"What is the national animal of Australia?", correct:"Kangaroo", wrong:["Koala","Emu","Platypus"] },
        { q:"How many strings does a standard guitar have?", correct:"6", wrong:["4","5","7"] },
    ],

    // ── 11: Entertainment: Film ──────────────────────────────
    11: [
        { q:"Who directed the 1993 film 'Schindler's List'?", correct:"Steven Spielberg", wrong:["Martin Scorsese","Francis Ford Coppola","Stanley Kubrick"] },
        { q:"Which film won the first Academy Award for Best Picture?", correct:"Wings (1927)", wrong:["Sunrise","The Jazz Singer","It"] },
        { q:"What is the highest-grossing film of all time (unadjusted)?", correct:"Avatar (2009)", wrong:["Avengers: Endgame","Titanic","Star Wars: The Force Awakens"] },
        { q:"Who played Iron Man in the Marvel Cinematic Universe?", correct:"Robert Downey Jr.", wrong:["Chris Evans","Chris Hemsworth","Mark Ruffalo"] },
        { q:"In which film does the line 'Here's looking at you, kid' appear?", correct:"Casablanca", wrong:["Gone with the Wind","Citizen Kane","The Maltese Falcon"] },
        { q:"Which animated film features the song 'Let It Go'?", correct:"Frozen", wrong:["Tangled","Brave","Moana"] },
        { q:"Who directed 'Pulp Fiction' (1994)?", correct:"Quentin Tarantino", wrong:["Joel Coen","David Fincher","Oliver Stone"] },
        { q:"Which actor has won the most Academy Awards for acting?", correct:"Meryl Streep", wrong:["Katharine Hepburn","Jack Nicholson","Daniel Day-Lewis"] },
        { q:"In 'The Matrix', what color pill does Neo take?", correct:"Red", wrong:["Blue","Green","White"] },
        { q:"Which film franchise features the character 'Jack Sparrow'?", correct:"Pirates of the Caribbean", wrong:["The Mummy","National Treasure","Treasure Planet"] },
        { q:"What year was the original 'Star Wars' released?", correct:"1977", wrong:["1975","1979","1980"] },
        { q:"Who played Forrest Gump in the 1994 film?", correct:"Tom Hanks", wrong:["Tom Cruise","Kevin Costner","John Travolta"] },
        { q:"Which film features the fictional African nation of Wakanda?", correct:"Black Panther", wrong:["Thor: Ragnarok","Captain America: Civil War","Avengers: Infinity War"] },
        { q:"What is the name of the toy cowboy in 'Toy Story'?", correct:"Woody", wrong:["Buzz","Rex","Hamm"] },
        { q:"Which director made 'Jurassic Park', 'E.T.', and 'Jaws'?", correct:"Steven Spielberg", wrong:["George Lucas","James Cameron","Ron Howard"] },
        { q:"In 'The Silence of the Lambs', what is Hannibal Lecter's profession?", correct:"Psychiatrist", wrong:["Surgeon","Lawyer","Professor"] },
        { q:"Which Bond film introduced the character Q?", correct:"From Russia with Love", wrong:["Dr. No","Goldfinger","Thunderball"] },
        { q:"What is the subtitle of the second 'Avengers' film?", correct:"Age of Ultron", wrong:["Infinity War","Endgame","Civil War"] },
        { q:"Who voiced Simba in the original 1994 'The Lion King'?", correct:"Matthew Broderick", wrong:["Jonathan Taylor Thomas","Jeremy Irons","James Earl Jones"] },
        { q:"Which film is set on the fictional planet Pandora?", correct:"Avatar", wrong:["Interstellar","Guardians of the Galaxy","The Martian"] },
        { q:"What is the name of the clownfish in 'Finding Nemo'?", correct:"Nemo", wrong:["Marlin","Gill","Dory"] },
        { q:"Who played the Joker in 'The Dark Knight' (2008)?", correct:"Heath Ledger", wrong:["Jack Nicholson","Jared Leto","Joaquin Phoenix"] },
        { q:"Which film won Best Picture at the 2020 Oscars?", correct:"Parasite", wrong:["1917","Joker","Once Upon a Time in Hollywood"] },
        { q:"In 'Home Alone', what city does Kevin's family travel to?", correct:"Paris", wrong:["London","New York","Miami"] },
        { q:"Which actress played Katniss Everdeen in 'The Hunger Games'?", correct:"Jennifer Lawrence", wrong:["Emma Watson","Shailene Woodley","Kristen Stewart"] },
    ],

    // ── 17: Science & Nature ─────────────────────────────────
    17: [
        { q:"What is the powerhouse of the cell?", correct:"Mitochondria", wrong:["Nucleus","Ribosome","Golgi apparatus"] },
        { q:"What is the chemical formula for water?", correct:"H₂O", wrong:["HO₂","H₂O₂","OH"] },
        { q:"How many chromosomes do humans normally have?", correct:"46", wrong:["44","48","23"] },
        { q:"What force keeps planets in orbit around the Sun?", correct:"Gravity", wrong:["Magnetism","Electromagnetism","Nuclear force"] },
        { q:"What is the most abundant element in the universe?", correct:"Hydrogen", wrong:["Helium","Oxygen","Carbon"] },
        { q:"What type of animal is a Komodo dragon?", correct:"Lizard", wrong:["Snake","Crocodilian","Turtle"] },
        { q:"What is the speed of sound in air at sea level (approx.)?", correct:"343 m/s", wrong:["220 m/s","500 m/s","1000 m/s"] },
        { q:"Which planet has the most moons?", correct:"Saturn", wrong:["Jupiter","Uranus","Neptune"] },
        { q:"What is the process by which plants make food using sunlight?", correct:"Photosynthesis", wrong:["Respiration","Fermentation","Transpiration"] },
        { q:"What is the atomic number of carbon?", correct:"6", wrong:["8","12","14"] },
        { q:"Which blood type is the universal donor?", correct:"O negative", wrong:["A positive","AB positive","B negative"] },
        { q:"What is the name of the force that opposes motion between surfaces?", correct:"Friction", wrong:["Tension","Compression","Torque"] },
        { q:"How long does it take light from the Sun to reach Earth?", correct:"About 8 minutes", wrong:["About 1 minute","About 1 hour","About 24 hours"] },
        { q:"What is the study of fungi called?", correct:"Mycology", wrong:["Botany","Zoology","Virology"] },
        { q:"Which gas is produced when acids react with metals?", correct:"Hydrogen", wrong:["Oxygen","Carbon dioxide","Nitrogen"] },
        { q:"What is the largest organ in the human body?", correct:"Skin", wrong:["Liver","Brain","Intestine"] },
        { q:"What is the name of the process by which a solid turns directly into a gas?", correct:"Sublimation", wrong:["Evaporation","Condensation","Deposition"] },
        { q:"Which planet rotates on its side (axial tilt ~98°)?", correct:"Uranus", wrong:["Neptune","Saturn","Venus"] },
        { q:"What is the unit of electrical resistance?", correct:"Ohm", wrong:["Volt","Ampere","Watt"] },
        { q:"What type of bond involves the sharing of electron pairs?", correct:"Covalent bond", wrong:["Ionic bond","Metallic bond","Hydrogen bond"] },
        { q:"What is the name of the protein that carries oxygen in red blood cells?", correct:"Hemoglobin", wrong:["Myoglobin","Albumin","Fibrin"] },
        { q:"Which law states that energy cannot be created or destroyed?", correct:"First Law of Thermodynamics", wrong:["Second Law of Thermodynamics","Newton's First Law","Ohm's Law"] },
        { q:"What is the most common type of star in the Milky Way?", correct:"Red dwarf", wrong:["Yellow dwarf","White dwarf","Blue giant"] },
        { q:"What is the pH of pure water?", correct:"7", wrong:["6","8","5"] },
        { q:"Which vitamin is produced when skin is exposed to sunlight?", correct:"Vitamin D", wrong:["Vitamin C","Vitamin A","Vitamin K"] },
    ],

    // ── 21: Sports ───────────────────────────────────────────
    21: [
        { q:"How many players are on a basketball team on the court at one time?", correct:"5", wrong:["6","4","7"] },
        { q:"In which sport would you perform a 'slam dunk'?", correct:"Basketball", wrong:["Volleyball","Handball","Water polo"] },
        { q:"How many Grand Slam tournaments are there in tennis?", correct:"4", wrong:["3","5","6"] },
        { q:"Which country has won the most FIFA World Cup titles?", correct:"Brazil", wrong:["Germany","Italy","Argentina"] },
        { q:"How long is a standard marathon in kilometers?", correct:"42.195 km", wrong:["40 km","45 km","38 km"] },
        { q:"In which sport is the 'Ryder Cup' contested?", correct:"Golf", wrong:["Tennis","Cricket","Polo"] },
        { q:"How many rings are on the Olympic flag?", correct:"5", wrong:["4","6","7"] },
        { q:"Which country hosted the 2016 Summer Olympics?", correct:"Brazil", wrong:["China","UK","Japan"] },
        { q:"In American football, how many points is a touchdown worth?", correct:"6", wrong:["7","5","4"] },
        { q:"What is the maximum score in a single game of ten-pin bowling?", correct:"300", wrong:["250","200","350"] },
        { q:"Which sport uses a 'shuttlecock'?", correct:"Badminton", wrong:["Squash","Racquetball","Pickleball"] },
        { q:"How many players are on a volleyball team on the court?", correct:"6", wrong:["5","7","8"] },
        { q:"In which city were the first modern Olympic Games held in 1896?", correct:"Athens", wrong:["Paris","London","Stockholm"] },
        { q:"What is the diameter of a basketball hoop in inches?", correct:"18 inches", wrong:["16 inches","20 inches","22 inches"] },
        { q:"Which boxer was known as 'The Greatest'?", correct:"Muhammad Ali", wrong:["Joe Frazier","Mike Tyson","Sugar Ray Leonard"] },
        { q:"How many holes are on a standard golf course?", correct:"18", wrong:["9","12","24"] },
        { q:"In which sport do players compete for the 'Stanley Cup'?", correct:"Ice Hockey", wrong:["Lacrosse","Curling","Bandy"] },
        { q:"What is the national sport of Japan?", correct:"Sumo wrestling", wrong:["Judo","Kendo","Baseball"] },
        { q:"How many sets are in a standard men's Grand Slam tennis match?", correct:"Best of 5", wrong:["Best of 3","Best of 7","Best of 4"] },
        { q:"Which country invented the sport of cricket?", correct:"England", wrong:["Australia","India","South Africa"] },
        { q:"In soccer, how many minutes are in a standard match?", correct:"90", wrong:["80","100","120"] },
        { q:"What is the term for three consecutive strikes in bowling?", correct:"Turkey", wrong:["Hat trick","Triple","Trifecta"] },
        { q:"Which swimmer has won the most Olympic gold medals?", correct:"Michael Phelps", wrong:["Mark Spitz","Ian Thorpe","Ryan Lochte"] },
        { q:"In which sport is a 'birdie' one under par?", correct:"Golf", wrong:["Badminton","Tennis","Squash"] },
        { q:"How many players are in a baseball team?", correct:"9", wrong:["10","8","11"] },
    ],

    // ── 22: Geography ────────────────────────────────────────
    22: [
        { q:"What is the capital of Canada?", correct:"Ottawa", wrong:["Toronto","Vancouver","Montreal"] },
        { q:"Which country has the largest land area?", correct:"Russia", wrong:["Canada","China","USA"] },
        { q:"What is the capital of Brazil?", correct:"Brasília", wrong:["São Paulo","Rio de Janeiro","Salvador"] },
        { q:"Which river flows through Egypt?", correct:"Nile", wrong:["Congo","Niger","Zambezi"] },
        { q:"What is the smallest continent by area?", correct:"Australia", wrong:["Europe","Antarctica","South America"] },
        { q:"Which country has the most people?", correct:"India", wrong:["China","USA","Indonesia"] },
        { q:"What is the capital of Japan?", correct:"Tokyo", wrong:["Osaka","Kyoto","Hiroshima"] },
        { q:"Which mountain range separates Europe from Asia?", correct:"Ural Mountains", wrong:["Caucasus","Alps","Carpathians"] },
        { q:"What is the largest country in South America?", correct:"Brazil", wrong:["Argentina","Colombia","Peru"] },
        { q:"Which sea lies between Europe and Africa?", correct:"Mediterranean Sea", wrong:["Red Sea","Black Sea","Caspian Sea"] },
        { q:"What is the capital of South Africa (administrative)?", correct:"Pretoria", wrong:["Cape Town","Johannesburg","Durban"] },
        { q:"Which country has the longest coastline?", correct:"Canada", wrong:["Russia","Norway","Indonesia"] },
        { q:"What is the capital of Argentina?", correct:"Buenos Aires", wrong:["Montevideo","Santiago","Lima"] },
        { q:"Which African country has the largest population?", correct:"Nigeria", wrong:["Ethiopia","Egypt","DR Congo"] },
        { q:"What is the capital of Germany?", correct:"Berlin", wrong:["Munich","Hamburg","Frankfurt"] },
        { q:"Which country is both in Europe and Asia?", correct:"Turkey", wrong:["Georgia","Kazakhstan","Armenia"] },
        { q:"What is the deepest lake in the world?", correct:"Lake Baikal", wrong:["Lake Tanganyika","Caspian Sea","Lake Superior"] },
        { q:"Which country contains the Amazon rainforest's largest portion?", correct:"Brazil", wrong:["Peru","Colombia","Venezuela"] },
        { q:"What is the capital of Egypt?", correct:"Cairo", wrong:["Alexandria","Luxor","Giza"] },
        { q:"Which strait separates Europe from Africa?", correct:"Strait of Gibraltar", wrong:["Strait of Hormuz","Bosphorus","Strait of Malacca"] },
        { q:"What is the capital of India?", correct:"New Delhi", wrong:["Mumbai","Kolkata","Chennai"] },
        { q:"Which country has the most UNESCO World Heritage Sites?", correct:"Italy", wrong:["China","Spain","France"] },
        { q:"What is the capital of Mexico?", correct:"Mexico City", wrong:["Guadalajara","Monterrey","Puebla"] },
        { q:"Which ocean is the smallest?", correct:"Arctic Ocean", wrong:["Indian Ocean","Southern Ocean","Atlantic Ocean"] },
        { q:"What is the capital of Nigeria?", correct:"Abuja", wrong:["Lagos","Kano","Ibadan"] },
    ],

    // ── 23: History ──────────────────────────────────────────
    23: [
        { q:"In which year did the Berlin Wall fall?", correct:"1989", wrong:["1991","1987","1985"] },
        { q:"Who was the first President of the United States?", correct:"George Washington", wrong:["John Adams","Thomas Jefferson","Benjamin Franklin"] },
        { q:"Which empire was ruled by Julius Caesar?", correct:"Roman Empire", wrong:["Greek Empire","Ottoman Empire","Byzantine Empire"] },
        { q:"In which year did the Titanic sink?", correct:"1912", wrong:["1910","1914","1908"] },
        { q:"Who was the first woman to win a Nobel Prize?", correct:"Marie Curie", wrong:["Rosalind Franklin","Dorothy Hodgkin","Lise Meitner"] },
        { q:"Which country was the first to give women the right to vote?", correct:"New Zealand", wrong:["Australia","Finland","Norway"] },
        { q:"In which year did the French Revolution begin?", correct:"1789", wrong:["1776","1799","1804"] },
        { q:"Who was the leader of the Soviet Union during World War II?", correct:"Joseph Stalin", wrong:["Vladimir Lenin","Nikita Khrushchev","Leon Trotsky"] },
        { q:"Which ancient wonder was located in Alexandria, Egypt?", correct:"Lighthouse of Alexandria", wrong:["Colossus of Rhodes","Hanging Gardens","Temple of Artemis"] },
        { q:"In which year did the United States declare independence?", correct:"1776", wrong:["1783","1775","1789"] },
        { q:"Who was the first person to walk on the Moon?", correct:"Neil Armstrong", wrong:["Buzz Aldrin","Yuri Gagarin","Alan Shepard"] },
        { q:"Which civilization built Machu Picchu?", correct:"Inca", wrong:["Aztec","Maya","Olmec"] },
        { q:"In which year did World War I begin?", correct:"1914", wrong:["1912","1916","1918"] },
        { q:"Who wrote the 'Communist Manifesto'?", correct:"Karl Marx and Friedrich Engels", wrong:["Vladimir Lenin","Leon Trotsky","Mao Zedong"] },
        { q:"Which country was the first to land a spacecraft on the Moon?", correct:"Soviet Union", wrong:["USA","China","UK"] },
        { q:"Who was the last Pharaoh of ancient Egypt?", correct:"Cleopatra VII", wrong:["Nefertiti","Hatshepsut","Ramesses II"] },
        { q:"In which city was the Magna Carta signed?", correct:"Runnymede (near Windsor)", wrong:["London","Canterbury","Oxford"] },
        { q:"Which war was fought between the North and South of the USA?", correct:"American Civil War", wrong:["War of 1812","Mexican-American War","Spanish-American War"] },
        { q:"Who was the first Emperor of China?", correct:"Qin Shi Huang", wrong:["Han Wudi","Tang Taizong","Kublai Khan"] },
        { q:"In which year did the Soviet Union dissolve?", correct:"1991", wrong:["1989","1993","1985"] },
        { q:"Which country did Napoleon Bonaparte come from?", correct:"France (born in Corsica)", wrong:["Italy","Spain","Austria"] },
        { q:"Who was the British Prime Minister during most of World War II?", correct:"Winston Churchill", wrong:["Neville Chamberlain","Clement Attlee","Anthony Eden"] },
        { q:"Which ancient city was destroyed by the eruption of Mount Vesuvius?", correct:"Pompeii", wrong:["Herculaneum","Stabiae","Oplontis"] },
        { q:"In which year did the Apollo 11 Moon landing occur?", correct:"1969", wrong:["1967","1971","1965"] },
        { q:"Who was the first female Prime Minister of the United Kingdom?", correct:"Margaret Thatcher", wrong:["Theresa May","Angela Merkel","Indira Gandhi"] },
    ],

    // ── 25: Art & Literature ─────────────────────────────────
    25: [
        { q:"Who wrote 'Romeo and Juliet'?", correct:"William Shakespeare", wrong:["Christopher Marlowe","Ben Jonson","John Milton"] },
        { q:"Which artist cut off part of his own ear?", correct:"Vincent van Gogh", wrong:["Paul Gauguin","Paul Cézanne","Georges Seurat"] },
        { q:"Who wrote '1984'?", correct:"George Orwell", wrong:["Aldous Huxley","Ray Bradbury","H.G. Wells"] },
        { q:"Which painting features a woman with a mysterious smile?", correct:"Mona Lisa", wrong:["The Birth of Venus","Girl with a Pearl Earring","Lady with an Ermine"] },
        { q:"Who wrote 'Pride and Prejudice'?", correct:"Jane Austen", wrong:["Charlotte Brontë","George Eliot","Mary Shelley"] },
        { q:"Which artist painted the Sistine Chapel ceiling?", correct:"Michelangelo", wrong:["Leonardo da Vinci","Raphael","Botticelli"] },
        { q:"Who wrote 'The Great Gatsby'?", correct:"F. Scott Fitzgerald", wrong:["Ernest Hemingway","John Steinbeck","William Faulkner"] },
        { q:"Which art movement is Salvador Dalí associated with?", correct:"Surrealism", wrong:["Cubism","Dadaism","Expressionism"] },
        { q:"Who wrote 'Don Quixote'?", correct:"Miguel de Cervantes", wrong:["Lope de Vega","Francisco de Quevedo","Tirso de Molina"] },
        { q:"Which Dutch master painted 'Girl with a Pearl Earring'?", correct:"Johannes Vermeer", wrong:["Rembrandt","Frans Hals","Jan Steen"] },
        { q:"Who wrote 'The Odyssey'?", correct:"Homer", wrong:["Virgil","Sophocles","Euripides"] },
        { q:"Which art style is characterized by small, distinct dots of color?", correct:"Pointillism", wrong:["Impressionism","Fauvism","Cubism"] },
        { q:"Who wrote 'Crime and Punishment'?", correct:"Fyodor Dostoevsky", wrong:["Leo Tolstoy","Anton Chekhov","Ivan Turgenev"] },
        { q:"Which artist is known for the 'Campbell's Soup Cans' series?", correct:"Andy Warhol", wrong:["Roy Lichtenstein","Jasper Johns","Robert Rauschenberg"] },
        { q:"Who wrote 'To Kill a Mockingbird'?", correct:"Harper Lee", wrong:["Truman Capote","John Steinbeck","William Faulkner"] },
        { q:"Which sculpture depicts a man in deep thought with his chin resting on his fist?", correct:"The Thinker", wrong:["David","Discus Thrower","Venus de Milo"] },
        { q:"Who wrote 'Harry Potter'?", correct:"J.K. Rowling", wrong:["Roald Dahl","C.S. Lewis","Philip Pullman"] },
        { q:"Which movement in art rejected traditional forms in favor of experimentation?", correct:"Modernism", wrong:["Romanticism","Neoclassicism","Baroque"] },
        { q:"Who wrote 'The Divine Comedy'?", correct:"Dante Alighieri", wrong:["Petrarch","Boccaccio","Virgil"] },
        { q:"Which artist is famous for 'Water Lilies'?", correct:"Claude Monet", wrong:["Pierre-Auguste Renoir","Edgar Degas","Camille Pissarro"] },
        { q:"Who wrote 'Brave New World'?", correct:"Aldous Huxley", wrong:["George Orwell","H.G. Wells","Ray Bradbury"] },
        { q:"Which building is considered the finest example of Gothic architecture?", correct:"Notre-Dame Cathedral", wrong:["Chartres Cathedral","Cologne Cathedral","Westminster Abbey"] },
        { q:"Who wrote 'The Catcher in the Rye'?", correct:"J.D. Salinger", wrong:["Jack Kerouac","John Updike","Philip Roth"] },
        { q:"Which Spanish artist co-founded Cubism?", correct:"Pablo Picasso", wrong:["Joan Miró","Salvador Dalí","Francisco Goya"] },
        { q:"Who wrote 'Moby-Dick'?", correct:"Herman Melville", wrong:["Nathaniel Hawthorne","Edgar Allan Poe","Mark Twain"] },
        // ── 20 additional Art & Literature ──
        { q:"Which novel begins with 'Call me Ishmael'?", correct:"Moby-Dick", wrong:["Billy Budd","The Scarlet Letter","The Old Man and the Sea"] },
        { q:"Who sculpted 'The Birth of Venus' painting?", correct:"Sandro Botticelli", wrong:["Raphael","Titian","Caravaggio"] },
        { q:"Which poet wrote 'The Waste Land'?", correct:"T.S. Eliot", wrong:["W.B. Yeats","Ezra Pound","W.H. Auden"] },
        { q:"What art movement is characterized by everyday objects as art?", correct:"Pop Art", wrong:["Abstract Expressionism","Minimalism","Conceptual Art"] },
        { q:"Who wrote 'One Hundred Years of Solitude'?", correct:"Gabriel García Márquez", wrong:["Jorge Luis Borges","Pablo Neruda","Mario Vargas Llosa"] },
        { q:"Which Shakespeare play features the character Iago?", correct:"Othello", wrong:["Macbeth","Hamlet","King Lear"] },
        { q:"Who painted 'The Starry Night'?", correct:"Vincent van Gogh", wrong:["Paul Gauguin","Georges Seurat","Henri Rousseau"] },
        { q:"Which Russian author wrote 'War and Peace'?", correct:"Leo Tolstoy", wrong:["Fyodor Dostoevsky","Ivan Turgenev","Nikolai Gogol"] },
        { q:"What is the name of the architectural style featuring pointed arches and flying buttresses?", correct:"Gothic", wrong:["Romanesque","Baroque","Renaissance"] },
        { q:"Who wrote 'The Metamorphosis'?", correct:"Franz Kafka", wrong:["Albert Camus","Jean-Paul Sartre","Samuel Beckett"] },
        { q:"Which artist is known for the 'Persistence of Memory' (melting clocks)?", correct:"Salvador Dalí", wrong:["René Magritte","Max Ernst","Joan Miró"] },
        { q:"Who wrote 'Beloved'?", correct:"Toni Morrison", wrong:["Alice Walker","Maya Angelou","Zora Neale Hurston"] },
        { q:"Which ancient Greek philosopher wrote 'The Republic'?", correct:"Plato", wrong:["Aristotle","Socrates","Epicurus"] },
        { q:"What is the term for a 14-line poem?", correct:"Sonnet", wrong:["Haiku","Ode","Villanelle"] },
        { q:"Who painted the ceiling of the Sistine Chapel?", correct:"Michelangelo", wrong:["Raphael","Leonardo da Vinci","Botticelli"] },
        { q:"Which novel features the character Jay Gatsby?", correct:"The Great Gatsby", wrong:["Tender is the Night","This Side of Paradise","The Sun Also Rises"] },
        { q:"Who wrote 'Frankenstein'?", correct:"Mary Shelley", wrong:["Ann Radcliffe","Jane Austen","Charlotte Brontë"] },
        { q:"Which Impressionist painter is known for ballet scenes?", correct:"Edgar Degas", wrong:["Pierre-Auguste Renoir","Claude Monet","Camille Pissarro"] },
        { q:"Who wrote 'The Iliad'?", correct:"Homer", wrong:["Virgil","Ovid","Hesiod"] },
        { q:"Which art movement rejected reason in favor of chaos and absurdity?", correct:"Dadaism", wrong:["Surrealism","Futurism","Expressionism"] },
    ],
};

// ── Additional questions appended to each category ──────────

// General Knowledge extras
TRIVIA_QUESTIONS[9].push(
    { q:"What is the currency of the United Kingdom?", correct:"Pound Sterling", wrong:["Euro","Dollar","Franc"] },
    { q:"How many planets are in our solar system?", correct:"8", wrong:["9","7","10"] },
    { q:"What is the largest mammal on Earth?", correct:"Blue whale", wrong:["African elephant","Sperm whale","Giraffe"] },
    { q:"Which country has the most time zones?", correct:"France", wrong:["Russia","USA","China"] },
    { q:"What is the boiling point of water at sea level in Celsius?", correct:"100°C", wrong:["90°C","110°C","212°C"] },
    { q:"How many letters are in the English alphabet?", correct:"26", wrong:["24","28","25"] },
    { q:"What is the name of the force that causes objects to fall?", correct:"Gravity", wrong:["Magnetism","Friction","Inertia"] },
    { q:"Which country is home to the kangaroo?", correct:"Australia", wrong:["New Zealand","South Africa","Brazil"] },
    { q:"What is the largest continent by area?", correct:"Asia", wrong:["Africa","North America","Europe"] },
    { q:"How many hours are in a week?", correct:"168", wrong:["144","196","160"] },
    { q:"What is the chemical symbol for iron?", correct:"Fe", wrong:["Ir","In","Io"] },
    { q:"Which gas makes up most of the air we breathe?", correct:"Nitrogen", wrong:["Oxygen","Carbon dioxide","Argon"] },
    { q:"What is the tallest animal in the world?", correct:"Giraffe", wrong:["Elephant","Ostrich","Camel"] },
    { q:"How many days are in a leap year?", correct:"366", wrong:["365","367","364"] },
    { q:"What is the capital of France?", correct:"Paris", wrong:["Lyon","Marseille","Bordeaux"] },
    { q:"Which ocean lies between Africa and Australia?", correct:"Indian Ocean", wrong:["Pacific Ocean","Atlantic Ocean","Southern Ocean"] },
    { q:"What is the most common blood type in humans?", correct:"O positive", wrong:["A positive","B positive","AB positive"] },
    { q:"How many zeros are in one million?", correct:"6", wrong:["5","7","9"] },
    { q:"What is the name of the longest bone in the human body?", correct:"Femur", wrong:["Tibia","Humerus","Fibula"] },
    { q:"Which planet is closest to the Sun?", correct:"Mercury", wrong:["Venus","Earth","Mars"] }
);

// Film extras
TRIVIA_QUESTIONS[11].push(
    { q:"Which film features the quote 'I'll be back'?", correct:"The Terminator", wrong:["Predator","RoboCop","Total Recall"] },
    { q:"Who directed 'The Godfather'?", correct:"Francis Ford Coppola", wrong:["Martin Scorsese","Brian De Palma","Sidney Lumet"] },
    { q:"Which film won the most Academy Awards ever (11 wins)?", correct:"Ben-Hur / Titanic / The Lord of the Rings: The Return of the King (tied)", wrong:["Gone with the Wind","Lawrence of Arabia","Schindler's List"] },
    { q:"What is the name of the fictional kingdom in 'Frozen'?", correct:"Arendelle", wrong:["Agrabah","Corona","Dunbroch"] },
    { q:"Who played Wolverine in the X-Men film series?", correct:"Hugh Jackman", wrong:["Russell Crowe","Eric Bana","Daniel Craig"] },
    { q:"Which film features a character named 'The Dude'?", correct:"The Big Lebowski", wrong:["Fargo","Barton Fink","Burn After Reading"] },
    { q:"In which film does a character say 'You can't handle the truth!'?", correct:"A Few Good Men", wrong:["The Firm","Philadelphia","JFK"] },
    { q:"Who directed 'Schindler's List'?", correct:"Steven Spielberg", wrong:["Roman Polanski","Sydney Pollack","Oliver Stone"] },
    { q:"Which animated studio produced 'Spirited Away'?", correct:"Studio Ghibli", wrong:["Pixar","DreamWorks","Toei Animation"] },
    { q:"What year was 'Citizen Kane' released?", correct:"1941", wrong:["1939","1944","1937"] },
    { q:"Who played the title role in 'Erin Brockovich' (2000)?", correct:"Julia Roberts", wrong:["Sandra Bullock","Meg Ryan","Michelle Pfeiffer"] },
    { q:"Which film franchise features the 'Decepticons'?", correct:"Transformers", wrong:["G.I. Joe","Power Rangers","Pacific Rim"] },
    { q:"What is the highest-grossing animated film of all time?", correct:"The Lion King (2019)", wrong:["Frozen II","Incredibles 2","Finding Dory"] },
    { q:"Who directed '2001: A Space Odyssey'?", correct:"Stanley Kubrick", wrong:["Ridley Scott","George Lucas","Steven Spielberg"] },
    { q:"Which film features the song 'My Heart Will Go On'?", correct:"Titanic", wrong:["Ghost","The Bodyguard","Dirty Dancing"] },
    { q:"What is the name of the shark in 'Finding Nemo'?", correct:"Bruce", wrong:["Jaws","Anchor","Chum"] },
    { q:"Who played Katniss Everdeen in 'The Hunger Games'?", correct:"Jennifer Lawrence", wrong:["Emma Watson","Shailene Woodley","Kristen Stewart"] },
    { q:"Which film is set in the fictional city of Gotham?", correct:"Batman", wrong:["Superman","Spider-Man","Iron Man"] },
    { q:"Who directed 'Inception' (2010)?", correct:"Christopher Nolan", wrong:["Darren Aronofsky","David Fincher","Denis Villeneuve"] },
    { q:"Which 1999 film features a 'bullet time' effect?", correct:"The Matrix", wrong:["Dark City","eXistenZ","Strange Days"] }
);

// Science & Nature extras
TRIVIA_QUESTIONS[17].push(
    { q:"What is the chemical symbol for sodium?", correct:"Na", wrong:["So","Sd","Sn"] },
    { q:"How many chambers does the human heart have?", correct:"4", wrong:["2","3","6"] },
    { q:"What is the closest star to Earth (after the Sun)?", correct:"Proxima Centauri", wrong:["Alpha Centauri A","Barnard's Star","Sirius"] },
    { q:"What is the process by which water vapor turns into liquid?", correct:"Condensation", wrong:["Evaporation","Sublimation","Precipitation"] },
    { q:"Which organ filters blood and produces bile?", correct:"Liver", wrong:["Kidney","Pancreas","Spleen"] },
    { q:"What is the name of the force that resists the relative motion of solid surfaces?", correct:"Friction", wrong:["Gravity","Tension","Normal force"] },
    { q:"How many bones are in the human skull?", correct:"22", wrong:["8","14","28"] },
    { q:"What is the chemical formula for table salt?", correct:"NaCl", wrong:["KCl","CaCl₂","MgCl₂"] },
    { q:"Which planet has the Great Red Spot?", correct:"Jupiter", wrong:["Saturn","Neptune","Mars"] },
    { q:"What is the name of the process by which cells divide?", correct:"Mitosis", wrong:["Meiosis","Osmosis","Diffusion"] },
    { q:"What is the unit of frequency?", correct:"Hertz", wrong:["Watt","Joule","Newton"] },
    { q:"Which element is a liquid at room temperature (besides mercury)?", correct:"Bromine", wrong:["Gallium","Cesium","Francium"] },
    { q:"What is the name of the layer of the atmosphere closest to Earth?", correct:"Troposphere", wrong:["Stratosphere","Mesosphere","Thermosphere"] },
    { q:"How many pairs of chromosomes do humans have?", correct:"23", wrong:["22","24","46"] },
    { q:"What is the chemical symbol for potassium?", correct:"K", wrong:["Po","Pt","Pu"] },
    { q:"Which scientist proposed the theory of general relativity?", correct:"Albert Einstein", wrong:["Isaac Newton","Niels Bohr","Max Planck"] },
    { q:"What is the name of the bone that protects the brain?", correct:"Skull (cranium)", wrong:["Sternum","Pelvis","Scapula"] },
    { q:"Which gas is produced by burning fossil fuels and contributes to climate change?", correct:"Carbon dioxide", wrong:["Methane","Nitrous oxide","Ozone"] },
    { q:"What is the name of the force that keeps electrons in orbit around the nucleus?", correct:"Electromagnetic force", wrong:["Gravitational force","Strong nuclear force","Weak nuclear force"] },
    { q:"What is the study of earthquakes called?", correct:"Seismology", wrong:["Geology","Volcanology","Tectonics"] }
);

// Sports extras
TRIVIA_QUESTIONS[21].push(
    { q:"In which sport is a 'hat trick' three goals by one player?", correct:"Soccer (Football)", wrong:["Hockey","Basketball","Rugby"] },
    { q:"How many points is a field goal worth in American football?", correct:"3", wrong:["2","4","6"] },
    { q:"Which country has won the most Olympic gold medals overall?", correct:"United States", wrong:["Soviet Union","China","Germany"] },
    { q:"What is the diameter of a tennis ball in inches?", correct:"2.5–2.625 inches", wrong:["2.0–2.25 inches","3.0–3.25 inches","1.5–1.75 inches"] },
    { q:"In which sport do players use a 'puck'?", correct:"Ice Hockey", wrong:["Lacrosse","Field Hockey","Polo"] },
    { q:"How many players are on a rugby union team?", correct:"15", wrong:["13","11","17"] },
    { q:"Which country invented basketball?", correct:"United States (by a Canadian)", wrong:["Canada","UK","Australia"] },
    { q:"What is the term for a score of zero in tennis?", correct:"Love", wrong:["Nil","Zero","Duck"] },
    { q:"How long is an Olympic swimming pool in meters?", correct:"50 meters", wrong:["25 meters","100 meters","75 meters"] },
    { q:"Which sport uses the term 'love-all'?", correct:"Tennis", wrong:["Badminton","Squash","Table Tennis"] },
    { q:"In which year were the first Winter Olympics held?", correct:"1924", wrong:["1920","1928","1932"] },
    { q:"What is the maximum weight of a golf ball in ounces?", correct:"1.62 oz", wrong:["1.5 oz","1.75 oz","2.0 oz"] },
    { q:"Which country has won the most Rugby World Cups?", correct:"New Zealand", wrong:["South Africa","Australia","England"] },
    { q:"How many events are in a decathlon?", correct:"10", wrong:["7","12","8"] },
    { q:"In which sport would you perform a 'Fosbury Flop'?", correct:"High Jump", wrong:["Pole Vault","Long Jump","Triple Jump"] },
    { q:"What is the name of the trophy awarded to the winner of the Tour de France?", correct:"There is no trophy — the winner wears the yellow jersey", wrong:["The Maillot d'Or","The Vélo d'Or","The Coupe de France"] },
    { q:"How many players are on a water polo team in the water?", correct:"7", wrong:["6","8","5"] },
    { q:"Which country hosted the 2022 FIFA World Cup?", correct:"Qatar", wrong:["Saudi Arabia","UAE","Bahrain"] },
    { q:"What is the term for a score of one under par in golf?", correct:"Birdie", wrong:["Eagle","Bogey","Par"] },
    { q:"In which sport is the 'Ashes' series contested?", correct:"Cricket", wrong:["Rugby","Tennis","Field Hockey"] }
);

// Geography extras
TRIVIA_QUESTIONS[22].push(
    { q:"What is the capital of Turkey?", correct:"Ankara", wrong:["Istanbul","Izmir","Bursa"] },
    { q:"Which country has the most islands?", correct:"Sweden", wrong:["Norway","Finland","Indonesia"] },
    { q:"What is the capital of South Korea?", correct:"Seoul", wrong:["Busan","Incheon","Daegu"] },
    { q:"Which river flows through London?", correct:"Thames", wrong:["Severn","Avon","Trent"] },
    { q:"What is the largest country in Africa by area?", correct:"Algeria", wrong:["Sudan","DR Congo","Libya"] },
    { q:"Which country is known as the 'Land of the Rising Sun'?", correct:"Japan", wrong:["China","South Korea","Thailand"] },
    { q:"What is the capital of Pakistan?", correct:"Islamabad", wrong:["Karachi","Lahore","Peshawar"] },
    { q:"Which mountain range contains Mount Everest?", correct:"Himalayas", wrong:["Karakoram","Hindu Kush","Pamir"] },
    { q:"What is the capital of Kenya?", correct:"Nairobi", wrong:["Mombasa","Kisumu","Nakuru"] },
    { q:"Which country has the longest land border?", correct:"China", wrong:["Russia","Brazil","USA"] },
    { q:"What is the capital of Indonesia?", correct:"Jakarta", wrong:["Bali","Surabaya","Bandung"] },
    { q:"Which sea is the saltiest in the world?", correct:"Dead Sea", wrong:["Red Sea","Caspian Sea","Aral Sea"] },
    { q:"What is the capital of Saudi Arabia?", correct:"Riyadh", wrong:["Jeddah","Mecca","Medina"] },
    { q:"Which country is home to the Amazon River's mouth?", correct:"Brazil", wrong:["Peru","Colombia","Venezuela"] },
    { q:"What is the capital of Ukraine?", correct:"Kyiv", wrong:["Kharkiv","Odessa","Lviv"] },
    { q:"Which country has the most volcanoes?", correct:"Indonesia", wrong:["Japan","USA","Philippines"] },
    { q:"What is the capital of Morocco?", correct:"Rabat", wrong:["Casablanca","Marrakech","Fez"] },
    { q:"Which country is the Sahara Desert primarily located in?", correct:"Algeria", wrong:["Libya","Egypt","Sudan"] },
    { q:"What is the capital of Peru?", correct:"Lima", wrong:["Cusco","Arequipa","Trujillo"] },
    { q:"Which country has the most freshwater?", correct:"Brazil", wrong:["Russia","Canada","China"] }
);

// History extras
TRIVIA_QUESTIONS[23].push(
    { q:"Which empire was the largest in history by land area?", correct:"Mongol Empire", wrong:["British Empire","Roman Empire","Russian Empire"] },
    { q:"In which year did the United States land on the Moon?", correct:"1969", wrong:["1967","1971","1965"] },
    { q:"Who was the first Emperor of Rome?", correct:"Augustus", wrong:["Julius Caesar","Nero","Caligula"] },
    { q:"Which war was fought between Athens and Sparta?", correct:"Peloponnesian War", wrong:["Persian Wars","Punic Wars","Macedonian Wars"] },
    { q:"In which year did the Russian Revolution occur?", correct:"1917", wrong:["1905","1921","1914"] },
    { q:"Who was the first female Pharaoh of Egypt?", correct:"Hatshepsut", wrong:["Cleopatra","Nefertiti","Nefertari"] },
    { q:"Which country was the first to use paper money?", correct:"China", wrong:["Persia","Rome","Egypt"] },
    { q:"In which year did the Great Fire of London occur?", correct:"1666", wrong:["1605","1688","1720"] },
    { q:"Who was the leader of the Cuban Revolution?", correct:"Fidel Castro", wrong:["Che Guevara","Raúl Castro","Camilo Cienfuegos"] },
    { q:"Which ancient civilization built the Colosseum?", correct:"Romans", wrong:["Greeks","Egyptians","Persians"] },
    { q:"In which year did India gain independence from Britain?", correct:"1947", wrong:["1945","1950","1942"] },
    { q:"Who was the first President of South Africa after apartheid?", correct:"Nelson Mandela", wrong:["Thabo Mbeki","F.W. de Klerk","Desmond Tutu"] },
    { q:"Which battle ended Napoleon's rule in 1815?", correct:"Battle of Waterloo", wrong:["Battle of Leipzig","Battle of Austerlitz","Battle of Trafalgar"] },
    { q:"In which year was the United Nations founded?", correct:"1945", wrong:["1919","1944","1948"] },
    { q:"Who was the first woman to fly solo across the Atlantic?", correct:"Amelia Earhart", wrong:["Bessie Coleman","Harriet Quimby","Jacqueline Cochran"] },
    { q:"Which country was the first to grant women the right to vote?", correct:"New Zealand", wrong:["Australia","Finland","Norway"] },
    { q:"In which year did the Chernobyl nuclear disaster occur?", correct:"1986", wrong:["1979","1991","1984"] },
    { q:"Who was the last Tsar of Russia?", correct:"Nicholas II", wrong:["Alexander III","Alexander II","Paul I"] },
    { q:"Which ancient wonder was located in Babylon?", correct:"Hanging Gardens of Babylon", wrong:["Colossus of Rhodes","Temple of Artemis","Lighthouse of Alexandria"] },
    { q:"In which year did the Korean War begin?", correct:"1950", wrong:["1948","1952","1945"] }
);
